### ISSUE TITLE
Get-Help could not find

### ISSUE THREAD

**Issue by bvi1998** [vmware/webcommander#101]
Hi,
I just upgraded to the latest version and am now getting the following error when I run the GetDefXML script...This script came with the update...
errMessage	Get-Help could not find C:\webcommander\powershell\AD\adNewDomain.ps1 in a help file in this session. To download updated help topics type: "Update-Help". To get help online, search for the help topic in the TechNet library at http://go.microsoft.com/fwlink/?LinkID=107116.
Also, I did run Update-Help on the wbc server. I am running PS 4.
Please let me know why I am seeing this? Thanks!

**Comment by 9whirls** [comment]
I couldn't reproduce the problem on my computer.
Please run the command below and post the output
get-help (get-command c:\webcommander\powershell\AD\adNewDomain.ps1).definition

**Comment by bvi1998** [comment]
I ran the above and it worked fine...

**Comment by bvi1998** [comment]
Where is the scriptpath param coming from? If I manually create the scriptpath variable the GetDefXML works.. 
Thanks!

**Comment by 9whirls** [comment]
https://github.com/vmware/webcommander/blob/master/powershell/genDefXml.ps1#L166

**Comment by bvi1998** [comment]
thx, I was looking  for it before the function, oops. 
The script runs fine locally, but not through the browser...

**Comment by 9whirls** [comment]
![image](https://cloud.githubusercontent.com/assets/7997931/11664221/5c9c8e54-9d95-11e5-9dbb-d7bf745839e7.png)
It works fine for me. What error did you get? Please post the source code the page.

**Comment by bvi1998** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/webCmd.xsl"?>
<webcommander cmd="genDefXml" developer="liuj@vmware.com" synopsis="Generate command definition" script="genDefXml">
  <description>This command generates _def.xml.
It parses all powershell scripts to get information from comment
based help and parameter attributes.</description>
  <parameters/>
  <result>
    <customizedOutput>[2015-12-08 15:20:51] Fail - get help of C:\webcommander\powershell\AD\adNewDomain.ps1</customizedOutput>
    <stderr>
      <exceptionType>Microsoft.PowerShell.Commands.HelpNotFoundException</exceptionType>
      <fullyQualifiedErrorId>HelpNotFound,Microsoft.PowerShell.Commands.GetHelpCommand</fullyQualifiedErrorId>
      <errMessage><![CDATA[Get-Help could not find C:\webcommander\powershell\AD\adNewDomain.ps1 in a help file in this session. To download updated help topics type: "Update-Help". To get help online, search for the help topic in the TechNet library at http://go.microsoft.com/fwlink/?LinkID=107116.]]></errMessage>
      <scriptName>C:\webcommander\powershell\genDefXml.ps1</scriptName>
      <scriptLineNumber>78</scriptLineNumber>
      <offsetInLine>11</offsetInLine>
    </stderr>
  </result>
  <returnCode>4444</returnCode>
  <executiontime>16.9 seconds</executiontime>
  <user>Administrator</user>
  <useragent>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</useragent>
  <useraddr>10.132.64.199</useraddr>
  <time>2015-12-08 15:20:52</time>
</webcommander>

**Comment by 9whirls** [comment]
We already confirmed that "get-help (get-command c:\webcommander\powershell\AD\adNewDomain.ps1).definition" works.
 Based on these two conflicting observations, I suspect what you saw in browser could come from local or proxy cache.
If not, I have to access your server for further investigation.

**Comment by 9whirls** [comment]
Wait, the source code shows <time>2015-12-08 15:20:52</time>. So this is not cache.
You could try rename adNewDomain.ps1 to adNewDomain.txt and run the command again. If that works, it means there is some syntex error in that script.

**Comment by bvi1998** [comment]
i built out a new vm and ran the installation from scratch. The problem went away. However, none of my scripts are working any longer. I am trying to run a simple script which runs the schtasks.exe command and it no longer works. Has something major changed? For instance, I do not need to run a PS session to run that command... 
Thanks for any help!

**Comment by 9whirls** [comment]
Does it also happen to the built-in scripts?
You have to provide more details (code, log, screenshot, etc.) so that I could help.

**Comment by bvi1998** [comment]
The builtin scripts I have tried fail because we have not yet enabled PS-Remoting on all servers. 
Here is a simple script I am trying to run. It runs from the Webcommander server locally, but not through WebCommander:

<#
	.SYNOPSIS
		Add User to Local Admin Group

	.DESCRIPTION
		This command adds a user or group to a local admin group
		
	.FUNCTIONALITY
		Windows
		
	.NOTES
		
#>
Param ( 

	[parameter(
        Mandatory=$true,
		HelpMessage="Server to add a user or group to the local Administrators Group"
	)]
	[string]
		$serverName,
    [parameter(
        Mandatory=$true,
		HelpMessage="User name or Group to add to the local Administrators Group (omit domain name)"
	)]
	[string]
		$trustee
)

foreach ($paramKey in $psboundparameters.keys) {
	$oldValue = $psboundparameters.item($paramKey)
	$newValue = [system.web.httputility]::urldecode("$oldValue")
	set-variable -name $paramKey -value $newValue
}

. "C:\webcommander\powershell\objects.ps1" 

$Trustee = 'WinNT://',"domainname",'/',$trustee -join ''

try {
	$Group = ([ADSI]"WinNT://$servername/Administrators,group")
    $Group.Add("$trustee,group")
    writeCustomizedMsg "Successfully completed command for `'$trustee`' on `'$servername`'"
} 
catch {
	writeCustomizedMsg "Adding `'$trustee`' on `'$servername`' was not Successful"
}

**Comment by 9whirls** [comment]
Would you please be more specific about the issue when you run through webcommander? At least post the source code of the returned web page.

When you run the script locally, what credential do you use? Local admin or domain admin?
You need to configure webcommander to run as the same user.

**Comment by bvi1998** [comment]
sure, here is the output:
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/webCmd.xsl"?>
<webcommander cmd="Set-ADAccountasLocalAdministrator" developer="" synopsis="Add User to Local Admin Group" script="Windows\Set-ADAccountasLocalAdministrator">
  <description>This command adds a user or group to a local admin group</description>
  <parameters>
    <parameter name="serverName" helpmessage="Server to add a user or group to the local Administrators Group" mandatory="1" value="server"/>
    <parameter name="guestUser" helpmessage="Guest user for target machine" mandatory="1" value="myid"/>
    <parameter name="guestPassword" helpmessage="Password of guestUser" mandatory="1" type="password" value="password"/>
    <parameter name="trustee" helpmessage="User name or Group to add to the local Administrators Group (omit domain name)" mandatory="1" value="usertobeadded"/>
  </parameters>
  <result>
    <customizedOutput>[2015-12-11 15:08:49] Adding 'WinNT://TTG/usertobeadded’ on 'server' was not Successful</customizedOutput>
  </result>
  <returnCode>4488</returnCode>
  <executiontime>3.9 seconds</executiontime>
  <user>sys_jennfair</user>
  <useragent>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</useragent>
  <useraddr>10.132.216.83</useraddr>
  <time>2015-12-11 15:08:50</time>
</webcommander>

**Comment by bvi1998** [comment]
The script works if I run as administrator or my id - I realized I missed the gathering of the username and pwd in my script. I have updated that, but still have the same problem. I can run the script as administrator or my id and it is successful. When running from WebCommander the result is my catch comment - not successful... 
Thanks!

**Comment by bvi1998** [comment]
![image](https://cloud.githubusercontent.com/assets/7153638/11746997/db3bf5aa-9fee-11e5-8abf-00b13904b08d.png)

**Comment by 9whirls** [comment]
you need to use the writestderr function to output the exception. It provides the real cause of the problem.

**Comment by bvi1998** [comment]
ah yes, previously the message was empty, but now getting:
exceptionType	System.Management.Automation.ExtendedTypeSystemException
fullyQualifiedErrorId	CatchFromBaseGetMember
errMessage	The following exception occurred while retrieving member "Add": "Access is denied. "
scriptName	C:\WebCommander\powershell\Windows\Set-ADAccountasLocalAdministrator.ps1
scriptLineNumber	57
offsetInLine	5

I am running this with either local admin or my id. When I run it locally as my id it works.

**Comment by 9whirls** [comment]
Output the two varibles below in your script to check what user the script is running as.
[Environment]::UserName

[Environment]::UserDomainName

**Comment by bvi1998** [comment]
the user name is my admin account, and the domain is correct.
I am also trying another script to schedule a task. When I use WebCommander it succeeds on the WebCommander server. When I try to run it on another server it fails.
Thanks!

**Comment by 9whirls** [comment]
Let's focus on one specific issue per issue report. 
Please also try to be more specific on describing "it fails".

Back to the original problem. I understand your were trying to add a user to the local admin group on a remote server, correct? Is the remote server in the same domain with webcommander server? And when your script connects to the remote server, does it use the same credential webcommander is running as?

To run commands on a remote machine, webcommander uses powershell remoting mechnism. If you have to use other ways, it's likely to hit some "second hop" issues. You could find more details at http://blogs.technet.com/b/heyscriptingguy/archive/2012/11/14/enable-powershell-quot-second-hop-quot-functionality-with-credssp.aspx

**Comment by bvi1998** [comment]
thanks, I will close this ticket now. I have modified my script to be included in the object.ps1
