### ISSUE TITLE
How to log off of WebCommander to log in as someone else

### ISSUE THREAD

**Issue by bvi1998** [vmware/webcommander#112]
Hi, 
I want to test my non-authoritative AD account to test it for other users. Is there a way to log off and on? If not, would it be easy enough to put a log in/log off up in the right hand corner of the page? 
Also, I thought I read it somewhere but cannot find it...how do we limit the scripts regular users can run,  ie what they see in the browser?
Thanks

**Comment by 9whirls** [comment]
If Windows Authentication is adopted, just to close browser and open it again for a cycle of logoff and logon.
Please note that if you use Chrome, you need to close all Chrome processes from task manager to completely logoff.

**Comment by bvi1998** [comment]
Also, I thought I read it somewhere but cannot find it...how do we limit the scripts regular users can run,  ie what they see in the browser?

**Comment by 9whirls** [comment]
Have a look at this discussion
https://github.com/vmware/webcommander/issues/51

**Comment by bvi1998** [comment]
Ok thanks I will try
