### ISSUE TITLE
Results/Output

### ISSUE THREAD

**Issue by bvi1998** [vmware/webcommander#115]
Hi, 
I am running a psexec command to install software on servers without Powershell. If I do a crtl-U after the job has finished, I can see the results have been captured... for instance:

</parameters>
  <result>
PsExec v1.98 - Execute processes remotely
Copyright (C) 2001-2010 Mark Russinovich
Sysinternals - www.sysinternals.com

How can I get this posted in the Results section of the WebCommander page? Psexec is tricky to get output from, but I see it is here and would like to use it in the Results section. 

Thanks for any assistance!
Jen

**Comment by 9whirls** [comment]
Please try the command below
$output = cmd /s /c "psexec.exe \\$ComputerName command to run 2>&1"

**Comment by bvi1998** [comment]
ok, I have found an issue. 

When I run the psexec command from WebCommander(in domain1) with my domain1 account to a domain1 server, the Event log says I am loggging in as domain1\id. This is correct.

When I run the psexec command from WebCommander(in domain1) with my domain1 account on a domain2 server, the Event log says I am loggging in as anonymous.

When I run either of the above from Powershell ISE they work perfectly, regardless of the domain.

Are there some other settings in IIS, or PHP that would fix this issue? 
Thanks for your help!
Jen

**Comment by 9whirls** [comment]
Could you run the psexec command from CMD (not Powershell ISE) with your domain1 account on a domain2 server?

**Comment by bvi1998** [comment]
yes, I ran the same command an it worked perfectly. In both cases I am running the command prompt and ISE at an elevated prompt.

**Comment by 9whirls** [comment]
Ok, please add the following line in your powershell script and run it from webcommander again
writeCustomizedMsg [Environment]::UserName

It shows the account whose credential is being used by webcommander. If it's different from the one you use to run the command from CMD and Powershell ISE, you need to configure IIS to run webcommander as that user.

You could refer to the installation guide about how to configure IIS.
https://github.com/vmware/webcommander/raw/master/www/images/wiki/IIS_Add_Website.png

**Comment by bvi1998** [comment]
ok, that was my problem the entire time, even trying to create a scheduled task. When using psexec, the software is actually on a network share, so administrator won't have access. I will go back to the scheduled task where I can control the user to run it. 
Thanks
