### ISSUE TITLE
Cannot install Windows Powershell 2.0 on Windows 2003

### ISSUE THREAD

**Issue by bvi1998** [vmware/webcommander#117]
Hi, 
I am running the VM\vmInstallPowershell script against a windows 2003 server. All I receive back is the following:

```
[2016-01-27 19:37:07] Success - connect to server vcenterservername
[2016-01-27 19:37:07] Info - server is of product line: VPX
```

Powershell is NOT installed on these Windows 2003 servers. I am trying to do the install.

I have placed the proper exe files into C:\WebCommander\postinstall\dotnet and C:\WebCommander\postinstall\powershell

Thanks!

**Comment by 9whirls** [comment]
What displays in the HTML source code?

**Comment by bvi1998** [comment]
sorry I forgot that :(

Result

    [2016-01-27 22:36:36] Success - connect to server ussrvwp-vcc01.ttg.global
    [2016-01-27 22:36:36] Info - server is of product line: VPX
    [2016-01-27 22:36:50] Info - Powershell Remoting is NOT enabled in target VM
    
    
    
    <result><customizedOutput>[2016-01-27 22:36:36] Success - connect to server ussrvwp-vcc01.ttg.global</customizedOutput><customizedOutput>[2016-01-27 22:36:36] Info - server is of product line: VPX</customizedOutput><customizedOutput>[2016-01-27 22:36:50] Info - Powershell Remoting is NOT enabled in target VM</customizedOutput>
Exception calling "enablePsRemote" with "0" argument(s): "Exception calling "installPs" with "0" argument(s): "Exception
calling "checkPs" with "0" argument(s): "Cannot convert value "'Powershell' is not recognized as an internal or external
command,
operable program or batch file.
" to type "System.Int32". Error: "Input string was not in a correct format.""""At
C:\WebCommander\powershell\VM\vmInstallPowershell.ps1:93 char:2
+     $vm.enablePsRemote()
+     ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ScriptMethodRuntimeException

**Comment by 9whirls** [comment]
Thanks for catching the bug.
Please pull latest objects.ps1 from master branch and try again.

**Comment by bvi1998** [comment]
ok I got further thanks. It copied the .net file down. Now I am getting:
XML Parsing Error: no element found
Location: http://wecommanderserver/webcmd.php?command=vmInstallPowershell
Line Number 1, Column 1:

and there is nothing available for source in the browser.

**Comment by 9whirls** [comment]
run the script on webcommander server
Cd c:\webcommander\powershell
.\vm\vminstallpowershell.ps1 -serveraddresss … …

Post the output and then we could debug further
