### ISSUE TITLE
Install issues.....

### ISSUE THREAD

**Issue by mikemast01** [vmware/webcommander#119]
I follow the install and config page, but when i go to the webcommander page on my server I get "This XML file does not appear to have any style information associated with it. The document tree is shown below."....   and then it shows me the index.xsl text on the screen.
I fell like I missed something, and went thru the document a few times and cant figure out what.. Thanks for any help in pointing me in the right direction.

Mike

**Comment by 9whirls** [comment]
Please open http://your_server_address/webcmd.php in your browser and post a screenshot and source code (right click on the page and select "view source") here.

**Comment by mikemast01** [comment]
![image](https://cloud.githubusercontent.com/assets/17012705/12731424/8b67b330-c8f6-11e5-88ff-37373e37079c.png)

**Comment by mikemast01** [comment]
<?xml version="1.0"?>


<?xml-stylesheet type="text/xsl" href="index.xsl" ?>
<webcommander xmlns:xi="http://www.w3.org/2003/XInclude">
  <command name="genDefXml" synopsis="Generate command definition" developer="liuj@vmware.com" xml:base="../powershell/_def.xml">
    <description>This command generates _def.xml.
It parses all powershell scripts to get information from comment
based help and parameter attributes.</description>
    <script>genDefXml</script>
  </command>
  <command name="pythonExample" synopsis="Example Python command" developer="liuj@vmware.com" xml:base="../python/_def.xml">
    <description>This is an example python command</description>
    <functionalities>
      <functionality>Python</functionality>
    </functionalities>
    <script>example.py</script>
    <parameters>
      <parameter name="myParam" helpmessage="Example parameter" mandatory="1"/>
    </parameters>
  </command>
  <command name="rubyExample" synopsis="Example Ruby command" developer="liuj@vmware.com" xml:base="../ruby/_def.xml">
    <description>This is an example ruby command</description>
    <functionalities>
      <functionality>Ruby</functionality>
    </functionalities>
    <script>example.rb</script>
    <parameters>
      <parameter name="myParam" helpmessage="Example parameter" mandatory="1"/>
    </parameters>
  </command>
  <command name="perlExample" synopsis="Example Perl command" developer="liuj@vmware.com" xml:base="../perl/_def.xml">
    <description>This is an example perl command</description>
    <functionalities>
      <functionality>Perl</functionality>
    </functionalities>
    <script>example.pl</script>
    <parameters>
      <parameter name="myParam" helpmessage="Example parameter" mandatory="1"/>
    </parameters>
  </command>
</webcommander>

**Comment by mikemast01** [comment]
It does not look like I can copy and paste the source...  So I attached it....

[source.txt](https://github.com/vmware/webcommander/files/113018/source.txt)

**Comment by 9whirls** [comment]
It works well. webcmd.php is the entry point. 
If you download from walnut branch, entry point is index.html

**Comment by mikemast01** [comment]
OK.. the site defaults to index.xsl when it is installed.. does that need to change to webcmd.php ?

**Comment by mikemast01** [comment]
so i Hve the webcommander-master..   should I use the walnut branch? what is the difference?

**Comment by 9whirls** [comment]
Yes, it's better to change webcmd.php to be the default.
If setup.ps1 works for you, this is configured automatically.
https://github.com/vmware/webcommander/blob/master/powershell/Install/setup.ps1#L167

**Comment by mikemast01** [comment]
it worked, but index.xsl was set as default.

PS C:\Users\admmmasters> C:\WebCommander\powershell\Install\setup.ps1
Downloading WPI ...
         WPI downloaded successfully.
Downloading WebCommander package...
         WebCommander package downloaded successfully
IIS is already installed.
Web Platform Installer is already installed.
PHP is already installed.
Extracting WebCommander package...
         WebCommander package extracted successfully.
Stopped all existing websites.
Creating WebCommander website...
         WebCommander website created successfully.
Configuring website authentication...
         Windows authentication is enabled.
Changing x86 Powershell profile...
         Powershell profile changed successfully.
Changing WSMAN settings...
         WSMAN settings changed successfully.
PS WSMan:\localhost\Client> C:\WebCommander\powershell\Install\setup.ps1

**Comment by 9whirls** [comment]
If you never used webcommander before, I recommend walnut because it contains all latest features.

**Comment by mikemast01** [comment]
Ok I will look into installing walnut and see... Thanks for the quick responses .

**Comment by 9whirls** [comment]
You are welcome. Please note that master and walnut to co-exist on the same server. 
Considering you already have master setup, you could just download walnut zip and extract it in the folder where you install master.

**Comment by mikemast01** [comment]
I got walnut working on another port another site, so I can look at both, while I get used to working with webcommander.

**Comment by 9whirls** [comment]
That's smart.

**Comment by 9whirls** [comment]
I forgot to mention yesterday. If you run walnut at any other port than 80, you need to modify sources.json to make local scripts show in the command list
https://github.com/vmware/webcommander/blob/walnut/sources.json#L2

**Comment by mikemast01** [comment]
in what file?  That is where I am a little confused, on this and I am trying to figure out. is how the scripts show up in the list, and how to make it so only certain ones show up in the list.?

**Comment by 9whirls** [comment]
In webcommander\sources.json, you could add multiple URLs to command definition files.
A command definition file, also in JSON format, includes mulitple script definitions.
The definition file could be generated automatially from powershell scripts by running genDefJson.ps1

**Comment by mikemast01** [comment]
Thanks, I am figuring this out as I go.
Is there a way to get rid of the "example perl/Pyton/ruby command" from showing up?  I modified the def file to get only the scripts I want to show, but those are still listed.

Thanks

**Comment by 9whirls** [comment]
Sorry, I was ralking about walnut.
For master, just remove perl, python and ruby folders.

**Comment by mikemast01** [comment]
Thanks so much, you are awesome.
I have been writing scripts for customers to use, and they run them thru citrix after I compile to a exe...  I have been looking for a web interface that would be better for users to use to create snaps, delete snaps and console access, and this looks great.

**Comment by 9whirls** [comment]
Cool. Once you feel comfortable to use webcommander, please think about contributing your scripts. Your valuable work could also benifit others!
BTW, do you mind let me know which company you work for?

**Comment by mikemast01** [comment]
Thanks , will do..    I work for Emerson.

http://www.emerson.com/en-us

**Comment by 9whirls** [comment]
Nice. Got 1 more fortune 500 user :)

**Comment by mikemast01** [comment]
LOL…

Web Commander will be a good starting point for me to develop something internally for us to use.

Mike Masters | VMware Administrator |
Emerson | 8000 W. Florissant Ave. | St. Louis | MO | 63136 | USA
T +1 314.553.2542 | F + 1 314.553.1491 | M +1 314.502.8914
CompTIA | A+ , Net + , Sec. +
VMWare | VCP 3,4,5   VCAP5-DCA
MCITP | 2008 SA/VA

**Comment by 9whirls** [comment]
That sounds a great plan!
Looking forward to getting your pull requests.

**Comment by 9whirls** [comment]
It is the same. Once you setup by following the wiki, copy walnut code to c:\webcommander\.
