### ISSUE TITLE
Console window

### ISSUE THREAD

**Issue by mikemast01** [vmware/webcommander#120]
I can open a console window fine from the web interface for virtual center. When i try thu commander it opens a new windows , but the console never loads, I do get any errors either.  any ideas?

Mike

**Comment by mikemast01** [comment]
Could there be an issue with permissions?  The server running webcommander is on a different domain than VC...   when I log into web commander, it is a different user  than what is used in the script to connect to VC, and that user has no rights to webcommander server or files?
Just a thought.

**Comment by 9whirls** [comment]
VMRC plugin (installed together with PowerCLI 5.5+) must be installed on the machine where you want to open VM console. Please try the following command and see if it works on your machine.
(get vm)[0] | Open-VMConsoleWindow

**Comment by mikemast01** [comment]
yes it is.. I can open VC webinterface in another tab and open the console so the plugin is installed and working.. but when I try to open the console from web commander tab, it opens a new tab with what looks like the vmware web console template, just like when I do it from VC... but the console screen never loads. Just a blank screen.
![image](https://cloud.githubusercontent.com/assets/17012705/12758496/25680b1e-c9a2-11e5-8c57-88ac3f2cddef.png)

**Comment by 9whirls** [comment]
![image](https://cloud.githubusercontent.com/assets/7997931/12758620/007a39e0-c992-11e5-9ba2-e750488300cb.png)

**Comment by 9whirls** [comment]
We you run the powershell command, what browser gets launched? Can it load vm console?
connect-viserver your_esx
(get vm)[0] | Open-VMConsoleWindow

**Comment by mikemast01** [comment]
Im looking now.. running from my  laptop.. webcommander is installed on a server in my datacenter. looks like I can open a console from VC webinterface fine, but that plugin is not installed as you show above...  I am working on getting powershell and the plugin on my laptop now, and will let you know.

Thanks so much.  I get better support on this than I do when I call for phone support on production issues...    :-)

Mike

**Comment by mikemast01** [comment]
looks to be same issue., it tries to open a file local to my laptop and still same...  as screen shot I sent above.

file:///C:/Program%20Files%20(x86)/VMware/Infrastructure/vSphere%20PowerCLI/VMConsoleWindow/VMConsoleWindow.html?host=mtnlabvc&vmid=vm-950&vmName=ESSTLL020-w001&ticket=cst-VCT-527b9022-f416-ee92-79bd-0ca407ccaa98--tp-C9-14-A6-53-49-53-AE-89-19-20-78-52-48-12-79-EF-C2-23-68-C0&tunnelConnection=0


I do show the plug-in installed.

**Comment by mikemast01** [comment]
![capture](https://cloud.githubusercontent.com/assets/17012705/12759335/1cc5808c-c9a6-11e5-8f98-6efe28d67df1.PNG)

**Comment by mikemast01** [comment]
I'm using IE... maybe I should try Firefox

**Comment by mikemast01** [comment]
Yep..   works in firefox...  not in IE.

**Comment by mikemast01** [comment]
Thanks again for helping / pointing me in the right direction.  I am getting closer to using this for a internal web interface to preform routine tasks for users without giving them VC access, or explaining how to do stuff in VC.. they just run the script for it.

**Comment by 9whirls** [comment]
Glad to know you got the issue solved. Please keep questions and feature requests coming. It's my pleasure to help.
