### ISSUE TITLE
way to change Parameter Value and Help Message Window?

### ISSUE THREAD

**Issue by bvi1998** [vmware/webcommander#122]
Hi, 

I have been asked by colleagues to change the webCommander parameter window to:

Help Message and Value - in that order, and only those. Is it possible for me to do that? 

Thanks!

**Comment by mikemast01** [comment]
Sorry, I am not sure I can help.. I am not sure what window you are talking about... maybe Jerry knows.

Mike

**Comment by 9whirls** [comment]
Hi,

If you mean to move the value column in the paramter table to the right of helpmessage column, you need to modify https://github.com/vmware/webcommander/blob/master/www/webCmd.xsl
1. move line 108 behind line 109
2. move line 209 before line 145

**Comment by mikemast01** [comment]
so does walnut use webcmd.xsl and master use index.xls?

**Comment by 9whirls** [comment]
Nope, walnut is JSON based. It has nothing to do with XML or XSL.

**Comment by mikemast01** [comment]
ok so index.xsl seems to be for webcmd.php.. I make changes to index.xsl and webcmd.php site changes.
I cant seem to figure out what webcmd.xsl is for ?

**Comment by 9whirls** [comment]
webcmd.xml is for each individual command, such as webcmd.php?command=adJoinDomain

**Comment by mikemast01** [comment]
Yeah that what I thought... but making a small change to the logo.. ( IE change webCommander to webbCommander)  save the file.   on index, it changes on the main page fine.  I change webcmd.xsl go to a command page webCmd.php?command=listVmAndSnapshot...    and it does not change, even after restarting IIS.      That is why I was confused a little..  
Thanks, I am working on tracking down what configs control which pages, and this is one I was having issue with.

**Comment by 9whirls** [comment]
What you referred to is https://github.com/vmware/webcommander/blob/master/www/webCmd.xsl#L73.
The xsl transform happens at client (browser) side. I suspect your browser cached webcmd.xsl so that you didn't observer the change you made. You could press shift+f5 to force browser download everything from server. If it dosn't work, you may need to emtpy all browser history and try again.

**Comment by mikemast01** [comment]
LOL... you are correct.. it was the cache..   I feel kinda stupid now...   :-)
I thought I figured that out , but when it did not change I was scratching my head, and thought maybe I was missing something...

Thanks Jerry.

**Comment by 9whirls** [comment]
You are welcome. 
Next time you find anything confusing, just raise a new question here.
