### ISSUE TITLE
scripting changes.

### ISSUE THREAD

**Issue by mikemast01** [vmware/webcommander#123]
On the snapshot script we limit users to one snapshot per VM. I am working on the modifying the script to look for an existing snapshot before creating a new one. And then a message telling them they must remove the current snapshot before creating new.

I am working on incorporating some of this into the webcommander scripting.. it does not need to automatically delete the snap, but just a message to run the script again and remove the snap before creating new snap.

Thanks, for any help in writing this, I am constantly improving my powershell knowledge.

Mike.
currently I use:

{
			$output = "Looking for a snapshot"
			Write-Progress -Activity "Snapshot..." -status $output
										
			######################
			#Snapshot Check
			########################
										
			$testSnap = Get-Snapshot -vm $VMName | Select VM,Name,Description,@{Label="Size";Expression={"{0:N2} GB" -f ($_.SizeGB)}},Created
								
			if (!($testSnap))
else				
			{
			
					Write-Host "*************************************************" -foregroundcolor Green
					Write-Host "*   There is an existing snapshot of  $VMName    *" -foregroundcolor Green
					Write-Host "*     Description =  $($testsnap.Description)    *" -foregroundcolor Magenta
					Write-Host "*     Created =  $($testsnap.Created)            *" -foregroundcolor Magenta
					Write-Host "*     Size =  $($testsnap.Size)                  *" -foregroundcolor Magenta
					Write-Host "*   Before a new snapshot can be taken the old   *" -foregroundcolor Green
					Write-Host "*          one needs to be deleted.              *" -foregroundcolor Green
					Write-Host "*	Please confirm  that you want to commit the  *" -foregroundcolor Green
					Write-Host "*   previous snapshot, and create a new snapshot.*" -foregroundcolor Green
					Write-Host "*************************************************" -foregroundcolor Green
					Write-Host -NoNewline -ForegroundColor Yellow "Please Enter Y to confirm that you want to commit the snapshot and proceed with a new snapshot -->"
					$YesNo = Read-Host 
					$YesNo = $YesNo.ToLower()
											
					if ($YesNo -eq "y")
					{
						Get-Snapshot -vm $VM |remove-snapshot -confirm:$false
						
			
							createsnapshot  $VMName $VM $PowerState

**Comment by 9whirls** [comment]
Could you be more specific about the question? What you described sounds very straightforward. 

You basically need to replace "write-host" with "writeCustomizedMsg" to output message in webcommander.

In addtion, your currently script requires user interaction (Read-Host) which is not supported by webcommander. All options must be defined as paramters before executing the script but not during the execution.

**Comment by mikemast01** [comment]
I think that answered most of the question... I don't really need the user ineraction.. just a message telling them to run script again and remove the snap..  I will work on it.  I also have other things I will be adding to the script as I go along.
Thanks.

Mike



Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------
