### ISSUE TITLE
Questions about releases

### ISSUE THREAD

**Issue by mikemast01** [vmware/webcommander#125]
Jerry,

Can you quickly explain to me the Differences between master and walnut?  I currently have the master installed, but before I got to far into the modifying the scripts I was wanting to make sure I understand the differences and if they both will be updated going forward.
Thanks 
Mike

**Comment by 9whirls** [comment]
Hi Mike,
I will only add new features into walnut later on. For master, just bug fixes.
Compared to master, walnut has the following Pros
1. Command definition and output are JSON instead of XML
2. Commands, sharing most parameters in common, are turned into methods of a single command. This removes duplicated parameter definitions, and organizes commands in an object oriented way.
3. Unified GUI of individual command and workflow
4. Changes (add,delete,update) to commands are effective during workflow execution
5. Users could save workflow on server
6. Could execute commands located on cloud without storing them locally on webcommander server
7. Execution history are stored in MongoDB

**Comment by mikemast01** [comment]
Thank Jerry,

Kinda what I figured.  I am going to install walnut then.  The download is listed as master..

How or what is needed to get walnut working?  It’s not real clear in the install instructions.

Mike Masters | VMware Administrator |
Emerson | 8000 W. Florissant Ave. | St. Louis | MO | 63136 | USA
T +1 314.553.2542 | F + 1 314.553.1491 | M +1 314.502.8914
CompTIA | A+ , Net + , Sec. +
VMWare | VCP 3,4,5   VCAP5-DCA
MCITP | 2008 SA/VA

**Comment by 9whirls** [comment]
Just copy all files to c:\webcommander\. Walnut and master could co-exist and work in the same place.
If you want to use MongoDB, you need to follow the wiki page to install and configure it.

**Comment by mikemast01** [comment]
Ok thanks.. if master is webcmd.php,  what is the start page for walnut?

Sorry for all the questions, I am trying to make sure I understand what/how it is configured.

Mike Masters | VMware Administrator |
Emerson | 8000 W. Florissant Ave. | St. Louis | MO | 63136 | USA
T +1 314.553.2542 | F + 1 314.553.1491 | M +1 314.502.8914
CompTIA | A+ , Net + , Sec. +
VMWare | VCP 3,4,5   VCAP5-DCA
MCITP | 2008 SA/VA

**Comment by 9whirls** [comment]
It's index.html. We talked about this on your day 1 :)
But you are right. This is something not clear enough.  I should write a setup.ps1 for walnut.

**Comment by mikemast01** [comment]
Thanks Again Sir.. I forgot about that.

I am writing it all down this time…     haha.

Mike Masters | VMware Administrator |
Emerson | 8000 W. Florissant Ave. | St. Louis | MO | 63136 | USA
T +1 314.553.2542 | F + 1 314.553.1491 | M +1 314.502.8914
CompTIA | A+ , Net + , Sec. +
VMWare | VCP 3,4,5   VCAP5-DCA
MCITP | 2008 SA/VA

**Comment by mikemast01** [comment]
We can talk about this tomorrow.  I got the walnut page to load but none of the links work..


I will look more tomorrow.

Mike Masters | VMware Administrator |
Emerson | 8000 W. Florissant Ave. | St. Louis | MO | 63136 | USA
T +1 314.553.2542 | F + 1 314.553.1491 | M +1 314.502.8914
CompTIA | A+ , Net + , Sec. +
VMWare | VCP 3,4,5   VCAP5-DCA
MCITP | 2008 SA/VA

**Comment by jrob24** [comment]
I am having the same issues. I saw that the index.html was using bit.ly to redirect to dropbox. Our company blocks all cloud storage sites, as I am sure a lot of companies do. So it might be something to consider for future releases. I copied the text from ui-min.css and ui-min.js and brought them locally and updated the index.html with the following:

<link rel="stylesheet" href="ui-min.css" type="text/css">
<script src="ui-min.js"></script>

However all of the styling is still missing and none of the icons are working. I must be still missing something. Any thoughts?

**Comment by jrob24** [comment]
Actually I believe that fixed the issue I was having. Amazing things happen after you clear your cache ;)

Mike,

Does Emerson block access to Dropbox? If so I bet you are running into the same issue I had. The solution above should work for you.

**Comment by jrob24** [comment]
Ok so I have it up, but the only scripts that are showing up are Workflow > Define Variable and Workflow > Sleep. What am I missing?

**Comment by mikemast01** [comment]
I will have to look tommorow.. can you post exactly  what you changed, and I will see.

Mike



Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by 9whirls** [comment]
Hi Jason, 
Does wells fargo block github?
If not, I could put a copy there.

**Comment by jrob24** [comment]
No they don't, we are allowed access to github.

**Comment by mikemast01** [comment]
![capture png - shortcut](https://cloud.githubusercontent.com/assets/17012705/12956097/d67f1704-cfeb-11e5-91d2-b919be5b4276.PNG)
Here is what I get on Walnut...  no Icons.

Please advise as to what may not be working.

Mike

**Comment by 9whirls** [comment]
There aren't icons in walnut. You need to select command on the bar. If the command contains multiple methods, there will be a parameter called method. It's also a dropdown list.

But the screen shot doesn't look correct. The command has many other parameters. Please empty browser cache and try again.

**Comment by mikemast01** [comment]
This is fine for Admins not having icons. Is there a way to get icons.?  I'm looking to make this for users to use also and the Icons like in master will be the best for users.

**Comment by 9whirls** [comment]
You want to display icons in the dropdown list of scripts and methods? That's doable. Let me try adding a few of them and see how they look in walnut UI.

For now, if icons are a must have, you have to use master.

**Comment by mikemast01** [comment]
Ok, that answers the question, that we cant get the big Icons that are in master into walnut.

**Comment by 9whirls** [comment]
Actually, we could still have an index page of big icons and add a link to each icon as http://webcommander/index.html?/exec.php?script=vsphere\vm\interfaces.ps1 
I just don't see much value in doing that.

**Comment by 9whirls** [comment]
![image](https://cloud.githubusercontent.com/assets/7997931/12965841/480833b6-d00e-11e5-9697-a28ba3d5ba28.png)
Github actually has a good example. I will try to turn the command selection into a similar one with icons.

**Comment by jrob24** [comment]
Any idea why this are the only scripts being displayed?

![image](https://cloud.githubusercontent.com/assets/12749455/12981333/d0cb95ca-d0a5-11e5-8f09-c6a1043dbbac.png)

**Comment by 9whirls** [comment]
Check sources.json. If you the URLs in that file are accessible.

**Comment by jrob24** [comment]
I removed remote and only let local:

{
  "local" : "http://localhost/_def.json",
}

However nothing changed.

**Comment by 9whirls** [comment]
So if you enter http://localhost/_def.json in your browser, could it return the json file?

**Comment by jrob24** [comment]
Yes it returns the contents of the json file.

**Comment by 9whirls** [comment]
Open "developer tool" in chrome, refresh the index page. Post the error messages you get from the console.

**Comment by jrob24** [comment]
![image](https://cloud.githubusercontent.com/assets/12749455/12987339/440ac7a2-d0c1-11e5-9412-e3777c97083b.png)

**Comment by 9whirls** [comment]
hmm, nothing explains the reason there. Because I couldn't reproduce the issue on my side, I don't know how to help further. Let me know if I could access your environment.

**Comment by jrob24** [comment]
I was able to get it to load, I forgot to remove the comma after _def.json in the sources.json file. It was an oversight on my part. 

I was playing around with a few of the scripts and it seems that the users password is saved in clear text in the .json history files and in the URL. In order to proceed any further with my testing I need to be able to disable storing any passwords in clear text. Where can I disable this functionality?

**Comment by 9whirls** [comment]
Woops, I didn't see that typo either.
As for the password issue, please read this https://github.com/vmware/webcommander/issues/86

For walnut, you need to modify exec.php 
https://github.com/vmware/webcommander/blob/walnut/www/exec.php#L220
