### ISSUE TITLE
addition to snapshot script so far.

### ISSUE THREAD

**Issue by mikemast01** [vmware/webcommander#127]
in my environment we only allow one snapshot per VM at a time and the snapshot is during the VM being powered off.  So I had to add tot he "Take" script to look for a previous snapshot, and to power off the VM before taking a snapshot, then powe on after.  Below is what I added so far, There will be more added as I go along, ( I.E.---   Checking for RDM disks and vmdk disks over 1.8 TB in size, each of those will cause a snapshot to fail.)

Mike

-----------------------------------------------------------------------------------------------------------------------------------

"take" {
			$vm.stop()
			
			Get-FloppyDrive -VM $vm.vivm | Set-FloppyDrive -NoMedia -Confirm:$False
			Get-CDDrive -VM $vm.vivm | Set-CDDrive -NoMedia -Confirm:$False 
			
            $testSnap = Get-Snapshot -vm $vm.vivm | Select VM,Name,Description,@{Label="Size";Expression={"{0:N2} GB" -f ($_.SizeGB)}},Created

                    if  ($testSnap -eq $null)
					{
						
						if ($vm.vivm.PowerState -ne "PoweredOff") 
						{
								try {
								stop-vm -vm $vm.vivm -confirm:$false -runAsync:$false -EA Stop
								writeCustomizedMsg "Success - shutdown VM $($_.name)"
								} catch {
									writeCustomizedMsg "Fail - shutdown VM $($_.name)"
									writeStderr
										}							
						}
						
						$vm.takeSnapshot($ssName,$ssDescription) 
					    
						if ($_.PowerState -ne "PoweredOn") 
						{
								try {
								Start-VM -vm $vm.vivm -confirm:$false -runAsync:$false -ea stop
								writeCustomizedMsg "Success - start VM $($_.name)"
								} catch {
									writeCustomizedMsg "Fail - start VM $($_.name)"
									writeStderr
										}
							 
						}
                    else {writeCustomizedMsg " There is an existing snapshot of $($vm.vivm) "
                             writeCustomizedMsg " Descrition =($($testsnap[($testsnap.count -1)].Description)) " 
							 writeCustomizedMsg " Created = ($($testsnap[($testsnap.count -1)].Created))"
							 writeCustomizedMsg " Size = ($($testsnap[($testsnap.count -1)].Size))"
							 writeCustomizedMsg " Before a new snapshot can be taken the old one needs to be removed."
							 writeCustomizedMsg "Please re-run the workflow and remove the snapshot"}
					
					}
					
				}

**Comment by 9whirls** [comment]
Mike, what's the issue?

**Comment by mikemast01** [comment]
no issue, just knowledge for anyone else.  was going to post elsewhere, but now sure where to post this info.

**Comment by 9whirls** [comment]
How about wiki?

**Comment by mikemast01** [comment]
Ahhh... thanks.. I missed the wiki thing for some reason.  I will post it there.

**Comment by 9whirls** [comment]
Sure. You could also post to your blog or personal website and add a link in wiki. It's your call.
