### ISSUE TITLE
interfaces.json

### ISSUE THREAD

**Issue by jrob24** [vmware/webcommander#128]
I have noticed there is a interfaces.json file for each interfaces.ps1 script that match the parameter names set in the powershell script. Is there a script to generate the interfaces.json file or does it have to be updated manually? 

It looks like the genDefJson.ps1 only updates the _def.jason file.

**Comment by 9whirls** [comment]
Hi Jason,

genDefJson.ps1 works as below:
1. Generate interfaces.json for each interfaces.ps1 if the json file doesnot exist.
2. Merge all interfaces.json into _def.json

If you manually create or modify interfaces.json files, they will not be overwritten unless you add -force update switch when you run genDefJson.ps1

**Comment by jrob24** [comment]
Ok so if I update an existing interfaces.ps1 script then I should delete the interfaces.json file so that the genDefJson.ps1 can re-generate it with the new parameters?

**Comment by 9whirls** [comment]
Correct
