### ISSUE TITLE
adding a new parameter value on the scipt page

### ISSUE THREAD

**Issue by mikemast01** [vmware/webcommander#129]
How would I add a new parameter value on a script page? I want to add another line in the snapshot action page to include a e-mail address. 
I found where and how to modify the current screen in the _def.xml, but how would I add a new parameter to show up. I have tried to add it in the _def.xml...

parameter name="E-Mail" helpmessage="E-Mail Address" mandatory="1" 

What else needs done for that to show on page?

Thanks

**Comment by jrob24** [comment]
Have you added the parameter to your script? Something like this:

[Parameter(
     Mandatory=$True,
     HelpMessage="E-Mail Address")]
[string[]]$emailAddress

After you add the parameter to your script you should be able to run genDefXml.ps1 which will update _def.xml for you. Then the parameter should show up in webcommander. The script will need to know how to handle the parameter once it is passed in, so make sure you have also added that. I use something like this:

if ($emailAddress){
	Send-MailMessage -To $emailAddress -From $From -SMTP $SMTPServer 
}

**Comment by mikemast01** [comment]
Thanks.. I will work on it and let you know.

**Comment by mikemast01** [comment]
I added the above parameter, and ran the script..the def.xml does not have that in there.

**Comment by jrob24** [comment]
Hmm, it should have added it to the _def.xml. You can manually add it, also you can run genDefXml.ps1 from a console and see if it is generating any errors. 

Can you post the parameters section of the script?

**Comment by mikemast01** [comment]
here is what is in the script.
	
		
	[Parameter(
		Mandatory=$True,
		HelpMessage="E-Mail Address"
	)]
	[string]
		$emailAddress,

**Comment by mikemast01** [comment]
here is what i get when I run genDefXml.ps1 

![image](https://cloud.githubusercontent.com/assets/17012705/13180695/30460810-d6ef-11e5-9978-04be0d8c09ac.png)

**Comment by 9whirls** [comment]
Cd c:\webcommander\powershell
.\gendefxml.ps1

**Comment by mikemast01** [comment]
thanks.. now I get ..

![image](https://cloud.githubusercontent.com/assets/17012705/13181534/346c9bb2-d6f3-11e5-823b-d8e89c058e17.png)

**Comment by jrob24** [comment]
What are the results if you run:

cd c:\webcommander\powershell\VM
Get-Help .\snapshotAction.ps1 -full

**Comment by mikemast01** [comment]
![image](https://cloud.githubusercontent.com/assets/17012705/13182757/fb552a6e-d6f8-11e5-8661-6bcae6bd9505.png)

**Comment by 9whirls** [comment]
in most cases, the error means a syntax error in the script.

**Comment by mikemast01** [comment]
Ok let me take out the parameter and see if it runs, maybe something did not copy right.

**Comment by mikemast01** [comment]
yeah, it does not like that parameter I put in, something must have copied wrong.. let me do it manually and see if that helps.

**Comment by mikemast01** [comment]
I manually put in the parameter...
		HelpMessage="Name of snapshot"
	)]
	[string]
		$ssName,
	
	[parameter(
		Mandatory=$true,
		HelpMessage="Action against the snapshot"
	)]
	[ValidateSet(
		"Take",
		"Restore",
		"Remove"
	)]
	[string]
		$action,
	
	[parameter(
		HelpMessage="Snapshot description"
	)]
	[string]
		$ssDescription=""
		
	[parameter(
		Mandatory=$true
		HelpMessage="eMail Address"
	)]
	[string]
		$emailaddress=""	
	
)


But when I run Get-Help .\snapshotAction.ps1 -full

I get 
![image](https://cloud.githubusercontent.com/assets/17012705/13187958/12604570-d714-11e5-974a-abdcfe9b2f6c.png)

**Comment by jrob24** [comment]
You are missing a comma after Mandatory=$true

**Comment by mikemast01** [comment]
Thanks for catching that..   but still no luck.. same error.

**Comment by jrob24** [comment]
So does it run with no errors if that parameter is removed?

**Comment by mikemast01** [comment]
Yes, I remove 

[parameter(
    Mandatory=$true
    HelpMessage="eMail Address"
)]
[string]
    $emailaddress=""   


And it runs with no errors.

**Comment by mikemast01** [comment]
PS C:\WebCommander\powershell\VM> Get-Help .\snapshotAction.ps1 -full

NAME
    C:\WebCommander\powershell\VM\snapshotAction.ps1

SYNOPSIS
    Take / restore / remove snapshot

SYNTAX
    C:\WebCommander\powershell\VM\snapshotAction.ps1 [-serverAddress] <String> [[-serverUser] <String>]
    [[-serverPassword] <String>] [-vmName] <String> [-ssName] <String> [-action] <String> [[-ssDescription] <String>]
    [<CommonParameters>]


DESCRIPTION
    This command takes, restores or removes a VM snapshot.
    This command could run against multiple virtual machines.


PARAMETERS
    -serverAddress <String>

        Required?                    true
        Position?                    1
        Default value
        Accept pipeline input?       false
        Accept wildcard characters?  false

    -serverUser <String>

        Required?                    false
        Position?                    2
        Default value                root
        Accept pipeline input?       false
        Accept wildcard characters?  false

    -serverPassword <String>

        Required?                    false
        Position?                    3
        Default value                $env:defaultPassword
        Accept pipeline input?       false
        Accept wildcard characters?  false

    -vmName <String>

        Required?                    true
        Position?                    4
        Default value
        Accept pipeline input?       false
        Accept wildcard characters?  false

    -ssName <String>

        Required?                    true
        Position?                    5
        Default value
        Accept pipeline input?       false
        Accept wildcard characters?  false

    -action <String>

        Required?                    true
        Position?                    6
        Default value
        Accept pipeline input?       false
        Accept wildcard characters?  false

    -ssDescription <String>

        Required?                    false
        Position?                    7
        Default value
        Accept pipeline input?       false
        Accept wildcard characters?  false

    <CommonParameters>
        This cmdlet supports the common parameters: Verbose, Debug,
        ErrorAction, ErrorVariable, WarningAction, WarningVariable,
        OutBuffer, PipelineVariable, and OutVariable. For more information, see
        about_CommonParameters (http://go.microsoft.com/fwlink/?LinkID=113216).

INPUTS

OUTPUTS

NOTES


        AUTHOR: Jerry Liu
        EMAIL: liuj@vmware.com


RELATED LINKS

**Comment by jrob24** [comment]
I really dont know, I just added the parameter to the snapshotAction.ps1 script and was able to run Get-Help -full on it with no errors. Can you please post the entire script?

**Comment by mikemast01** [comment]
[snapshotAction.txt](https://github.com/vmware/webcommander/files/138724/snapshotAction.txt)

**Comment by jrob24** [comment]
Sorry I meant can you post the entire script with the parameter added back in?

**Comment by mikemast01** [comment]
ok..  I will this weekend or Monday.. thanks

**Comment by mikemast01** [comment]
[snapshotAction (2).txt](https://github.com/vmware/webcommander/files/141470/snapshotAction.2.txt)


Here is the file with the parameter put back in. getting the  error when I run...
Get-Help .\snapshotAction.ps1 -full

![image](https://cloud.githubusercontent.com/assets/17012705/13233623/24fbe4e2-d97a-11e5-8a5c-80c7502737a9.png)

**Comment by jrob24** [comment]
Try adding a comma after Mandatory=$true, so it reads like:

    [parameter(
		Mandatory=$true,
		HelpMessage="eMail Address"
	)]
	[string]
		$emailaddress=""

Without the comma I got the same error you did, but when I added it the error went away.

**Comment by mikemast01** [comment]
You da Bomb..... !!!!!    I knew it had to be a little something I was missing.   Thanks it ran that time and it is showing now.

![image](https://cloud.githubusercontent.com/assets/17012705/13235051/8656d560-d981-11e5-98da-234ac3b444df.png)

**Comment by jrob24** [comment]
Great! Email away :)
