### ISSUE TITLE
Issue/question on a script

### ISSUE THREAD

**Issue by mikemast01** [vmware/webcommander#130]
I notice in the vmshutdown.ps1, there is the command to stop-vm.. which powers off the VM.
What command do you have in that does a graceful shutdown? The normal powershell commands don't seem to work. ( I.E. shutdown-vmguest)

**Comment by mikemast01** [comment]
The term 'Shutdown-VMGuest' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by mikemast01** [comment]
I can manually open powercli , connect and do a shutdown-VMguest command and that works... but when I run thru webcommander I get the above error.

**Comment by 9whirls** [comment]
Please post your code. I will have a look after getting back from vacation.

**Comment by mikemast01** [comment]
in vmshutdown script you have...
-----------------------------------------------------------------------------
stop-vm -vm $_ -confirm:$false -runAsync:$false -EA Stop
-----------------------------------------------------------------------------
Which is a power off command, and does not do a graceful shutdown.

I see in the objects.ps1 you call a command
-----------------------------------------------------------------------------------------------------------------
Shutdown-VMGuest -vm $this.vivm -server $this.server.viserver -confirm:$false | out-null
				start-sleep 30
------------------------------------------------------------------------------------------------------------------
When I try to put the command "shutdown-vmguest" intot he vmshutdown.ps1, i get an error thru webcommander that that command is not recognized as a valid cmdlet.

But I can open power shell on the server and run the command manually, I am trying to figure out why it will not run in commander.

**Comment by mikemast01** [comment]
LOL, I put lines in the comment to separate the commands from my comments and it BOLD some of the text instead... sorry.

**Comment by 9whirls** [comment]
The vm.stop() function defined in objects.ps1 tries shutdown-vmguest before calling stop-vm.

**Comment by mikemast01** [comment]
Which function? I am looking for it..
I search for vm.stop in objects.ps1 and it does not find that.
When I test the script, it powers off the vm and never tries a shutdown thru tools..  just does a power off.

Mike Masters | VMware Administrator |
Emerson | 8000 W. Florissant Ave. | St. Louis | MO | 63136 | USA
T +1 314.553.2542 | F + 1 314.553.1491 | M +1 314.502.8914
CompTIA | A+ , Net + , Sec. +
VMWare | VCP 3,4,5   VCAP5-DCA
MCITP | 2008 SA/VA

**Comment by mikemast01** [comment]
I see $vm.stop()   in the snapshot command, but not in objects.So its not doing anything
So I have in my command a stop-vm command is why it is powering off.

I notice in the vmshutdown.ps1, the command is a stop-vm also. and it is not calling the $vm.stop() function.

**Comment by mikemast01** [comment]
Ok I found in objects where it calls the function stop, and I see where it tries that. But it does neither in the script..  neither shutdown or power off.

	$vm = newVm $server $_.name
	writeCustomizedMsg "Info - VM name is $($vm.name)" }
	switch($action) {
		"take" {
			$vm.stop()
			

			Get-FloppyDrive -VM $vm.vivm | Set-FloppyDrive -NoMedia -Confirm:$False
			Get-CDDrive -VM $vm.vivm | Set-CDDrive -NoMedia -Confirm:$False

**Comment by mikemast01** [comment]
Now if I put this in the snapshot action script it powers off the VM .  But when it tries to call the function$vmstop it does nothing.

if ($vm.vivm.PowerState -ne "PoweredOff") 
						{
								try {
								stop-vm -vm $vm.vivm -confirm:$false -runAsync:$false -EA Stop
								writeCustomizedMsg "Success - shutdown VM $($_.name)"
								} catch {
									writeCustomizedMsg "Fail - shutdown VM $($_.name)"
									writeStderr
										}							
						}

**Comment by 9whirls** [comment]
Please post the entire script.

**Comment by mikemast01** [comment]
[snapshotAction.txt](https://github.com/vmware/webcommander/files/148604/snapshotAction.txt)

**Comment by mikemast01** [comment]
ok look at the vmshutdown script, I have not edited that at all from the download.
In that script you have it calling stop-vm, which will power off a VM and not do a shutdown of the OS...

**Comment by mikemast01** [comment]
Any idea on why the The vm.stop() function  , is not working in this script?

**Comment by 9whirls** [comment]
The built-in script could shutdown the VM in my environment
![image](https://cloud.githubusercontent.com/assets/7997931/13405914/a2f94adc-ded5-11e5-825a-4b9b0a1bd6af.png)

**Comment by 9whirls** [comment]
![Uploading image.png…]()
The built-in script works in my environment.

**Comment by mikemast01** [comment]
i put the original script back in from the compressed download and I run it .And it does not shutdown the server.

![image](https://cloud.githubusercontent.com/assets/17012705/13406289/493dba9c-dee8-11e5-8329-1e0506d90e9a.png)

**Comment by mikemast01** [comment]
This is all I see in VC.
![image](https://cloud.githubusercontent.com/assets/17012705/13406329/74d25b22-dee8-11e5-8e46-bc4a68d45f99.png)

**Comment by 9whirls** [comment]
Did you make any change to objects.ps1 (in the VM stop function)?

**Comment by mikemast01** [comment]
left is the active one, right is the original 
![image](https://cloud.githubusercontent.com/assets/17012705/13406555/c75745c8-dee9-11e5-8b3e-0cd82c3aa7f5.png)

**Comment by 9whirls** [comment]
I didn't observe any change there.
Please add the following commands at line 428 for debug purpose.
writeCustomizedMsg "Info - power state is $($this.vivm.powerstate)"

**Comment by mikemast01** [comment]
![image](https://cloud.githubusercontent.com/assets/17012705/13406941/a5c8cf06-deeb-11e5-9e90-64d3ec61cae9.png)

added that line , saved. and re-ran.

**Comment by mikemast01** [comment]
![image](https://cloud.githubusercontent.com/assets/17012705/13406945/ad7cece6-deeb-11e5-9cc0-6efc77a1039d.png)

**Comment by mikemast01** [comment]
Now if I run the snapshot script while the VM is powered off I get the message...

![image](https://cloud.githubusercontent.com/assets/17012705/13407027/217408b4-deec-11e5-9433-b812ec678c53.png)

**Comment by mikemast01** [comment]
Ok so I put this into the else command.

![image](https://cloud.githubusercontent.com/assets/17012705/13409268/d4bb0174-def7-11e5-9bd3-c5d19b99807f.png)

And when I run it it gets to the else command, but it never tries to do a shutdown, or ever a stop-vm command.

![image](https://cloud.githubusercontent.com/assets/17012705/13409300/f61d1118-def7-11e5-8935-ae16fb59e387.png)

**Comment by 9whirls** [comment]
Add the command below at the beginning of "do-while" section to check how many loops it executes
writeCustomizedMsg "Info - $i"

**Comment by mikemast01** [comment]
if I change the "shutdown-vmguest" command with a "stop-vm" command... the script executes that command.  It seems to have issues with the "shutdown-vmguest" command.

**Comment by mikemast01** [comment]
I added the command like you asked.
![image](https://cloud.githubusercontent.com/assets/17012705/13409762/0280128c-defa-11e5-8a16-bbec41765aa2.png)


 and this what i got.

![image](https://cloud.githubusercontent.com/assets/17012705/13409774/0c17c506-defa-11e5-8667-390871f7fd22.png)

**Comment by 9whirls** [comment]
You should add the command in the "do" loop.

Based on your previous comment (stop-vm works but shutdown-vmguest doesn't), remove " | out-null" and see what message the command outputs. You may need to open source code of the returned page to get it.

**Comment by mikemast01** [comment]
ok, not sure I understand "You may need to open source code of the returned page to get it."

**Comment by 9whirls** [comment]
It looks like in the latest PowerCLI version (6.0) the cmdlet is named stop-vmguest.
http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.powercli.cmdletref.doc/Stop-VMGuest.html?resultof=%2522%2573%2568%2575%2574%2564%256f%2577%256e%252d%2576%256d%2567%2575%2565%2573%2574%2522%2520

**Comment by 9whirls** [comment]
I meant "right click on the browser and select 'view source code' from the context menu".

**Comment by mikemast01** [comment]
OH..lol..   let me try the stop-vmguest and see if that works.

**Comment by mikemast01** [comment]
stop-vmguest did it....

![image](https://cloud.githubusercontent.com/assets/17012705/13410384/1bbf23ac-defd-11e5-85c0-ec14e0f177da.png)

**Comment by 9whirls** [comment]
hmm, no idea why they changed the cmdlet name.
Anyway, we get the issue solved. :)

**Comment by mikemast01** [comment]
yes, I got my script to work now, and it powers the vm back on , all in one script.
Thanks..  now onto other questions I have....
