### ISSUE TITLE
Results Not Displaying

### ISSUE THREAD

**Issue by jrob24** [vmware/webcommander#131]
I have a script added to Walnut and all of the parameters are showing up, however when I run the script no results are showing. It is a very basic script just to test displaying results. After the parameters here are the contents of the script. Also I noticed it always says Fail when I run the script. 

`. .\utils.ps1`
`addToResult "test"`
`writeResult`

**Comment by jrob24** [comment]
It runs perfectly inside the console.

![image](https://cloud.githubusercontent.com/assets/12749455/13191763/a446ecd4-d72b-11e5-8c2e-155f0fc14df3.png)

**Comment by 9whirls** [comment]
Could you see the message in the JSON tab?

**Comment by jrob24** [comment]
No, output is listed as null. 

` "output": null,
  "returncode": 4444,
  "executiontime": "4.2 seconds",`

**Comment by 9whirls** [comment]
try to run the script with the cmd below:
.\exec.ps1 -script vsphere\report\interfaces.ps1 -search …

**Comment by jrob24** [comment]
![image](https://cloud.githubusercontent.com/assets/12749455/13233532/b28ff3b2-d979-11e5-8b32-3a9444961c99.png)

**Comment by 9whirls** [comment]
It seems that exec.ps1 couldn't read your script.
you could set $env:runfromweb=$false and run the cmd again to show the error in console.

**Comment by jrob24** [comment]
![image](https://cloud.githubusercontent.com/assets/12749455/13234960/01084bfa-d981-11e5-93a4-b7b86a4d61c3.png)

**Comment by 9whirls** [comment]
I am sorry. Please remove "-script" from the command and try again.

**Comment by jrob24** [comment]
![image](https://cloud.githubusercontent.com/assets/12749455/13236990/c41765de-d98d-11e5-892b-cc6618652e60.png)

**Comment by 9whirls** [comment]
It works well. The output is correct.
Does the error only happen to the new script? How about built-in scripts?

**Comment by jrob24** [comment]
Correct, built in scripts run fine. I have only added one new script and noticed it was failing with no output.

**Comment by 9whirls** [comment]
But we just verified the new script runs well.

**Comment by jrob24** [comment]
That is correct it works from the console, but how come the script fails when it is ran from webCommander and no results are returned?

**Comment by 9whirls** [comment]
Could you edit a built in script to output the same message and check if it works?

**Comment by jrob24** [comment]
Same results, I dont understand I am just trying to write a sample output. I added the following to the vSphere (local) script. 

Added to the parameters:

    ##################### Start Test parameters #####################    
      [parameter(
    parameterSetName="test",
    Mandatory=$true,
    HelpMessage="test"
      )]
      [string]
      $test

Added to the switch statement:

    "test" {
  	addToResult "Testing output"	
      }

Results

![image](https://cloud.githubusercontent.com/assets/12749455/13239380/6659cb6e-d99f-11e5-9b88-1a760784e60a.png)

**Comment by 9whirls** [comment]
Please send the entire script to me. I will test it on my server.

**Comment by jrob24** [comment]
I was able to get it to work with the build-in scripts. I needed to change $test from a [string] to a [switch]. I am now going to do some more testing with my script.

**Comment by 9whirls** [comment]
OK, please let me know when you need my assistance.
