### ISSUE TITLE
IE 11 support?

### ISSUE THREAD

**Issue by mikemast01** [vmware/webcommander#132]
When I try to got webcommander using IE 11, I get the message that I need a browser that supports HTML5 like IE 10.

How can I change this check to support IE 11????

**Comment by 9whirls** [comment]
please check the code block at the bottom of webcmd.js.

**Comment by mikemast01** [comment]
OK, that changes the text ..    i am using IE11, so it should not prompt me for a newer browser.. where does it check for a browser version? and how can I get it to accept IE11 as a valid browser?

**Comment by 9whirls** [comment]
please just remove that code block.
