### ISSUE TITLE
buttons are not working

### ISSUE THREAD

**Issue by mikemast01** [vmware/webcommander#133]
any idea why the buttons will not work?  RUN, js and url dont do anything today?  Worked yesterday
Sorry to bother you on this, but right now I dont have an explanation. anything you know of that would cause them to not work? something in the browser.
 Are the keys funtions loaded from a external site?  I am looking thru it now.

Thanks

**Comment by 9whirls** [comment]
![image](https://cloud.githubusercontent.com/assets/7997931/13436989/d5880eb8-df96-11e5-9148-36a059f48155.png)
Open the developer tools console in browser and then click the button.
If something goes wrong, you could see error messages there.

**Comment by mikemast01** [comment]
I open the list vmsnapshot command and i see this.

![image](https://cloud.githubusercontent.com/assets/17012705/13437088/15c4fe94-dfa8-11e5-869e-8c91001cc452.png)

**Comment by 9whirls** [comment]
So your webcmd.js has syntax error at line 401.

**Comment by mikemast01** [comment]
Ahh.. thanks..   Thats where the comment out the incomparable browser section you said the other day. I made the change yesterday, maybe I did not save the file until I closed it out yesterday, and I did not see the effect till this morning.

I was freaking out for a min... now that you point that out, Hopefully I can figure this out if i have an issue again.

Thanks Jerry.

**Comment by 9whirls** [comment]
Always shift+f5 to avoid cache :)
