### ISSUE TITLE
IE not working

### ISSUE THREAD

**Issue by mikemast01** [vmware/webcommander#134]
I know I am a pain..   :-)

I cant get the console to work in IE.  I go to the vsphere web interface and can open the console from IE fine.  I try to run from webcommander and I get a blank screen..

![image](https://cloud.githubusercontent.com/assets/17012705/13439593/dea764d6-dfb3-11e5-8b3e-c7c2533eed74.png)
  and this error when I close the window..

![image](https://cloud.githubusercontent.com/assets/17012705/13439605/ecd03074-dfb3-11e5-8eb3-20fd66c8abae.png)

**Comment by 9whirls** [comment]
Not only this one. I couldn't even get some basic CSS or JS features work in IE. 
Considering Edge works well and Firefox / Chrome could all be installed on Windows, I won't spend much efforts to support IE. Sorry.
