### ISSUE TITLE
Parameter Order (Walnut)

### ISSUE THREAD

**Issue by jrob24** [vmware/webcommander#135]
How is the order of the parameters determined for displaying on the parameter screen? I tried using positional parameters to get them in the order I wanted but that doesn't seem to work. 

It appears that parameters not assigned to a parameterSet are shown first and then everything in sequential order after that. Is this correct? 

Is it possible to have them displayed a custom order determined by the script (method)?

**Comment by 9whirls** [comment]
You observation is correct. Parameters, not belong to any parameter set, are common to all methods. So they are list first. 

You could edit intefaces.json to change the order, and then run genDefJson.ps1 to merge into _def.json.

**Comment by jrob24** [comment]
Ok thats what it looked like. I dont really like having to manually update things, seems to defeat the purpose of automation :) 

Since position is a part of the parameters attributes it I will look to see if I can get it ordered by position.
