### ISSUE TITLE
Script History (Walnut)

### ISSUE THREAD

**Issue by jrob24** [vmware/webcommander#140]
Is there no history script available without using the MongoDB? 

I see all of the json files are saved under www\history, but I didn't see a history script available.

**Comment by 9whirls** [comment]
The history scipt is hosted remotely on dropbox.

**Comment by jrob24** [comment]
Ok that would be why I can't see it. I will look for it when I get home. Any chance you can move things from dropbox to Github?

**Comment by jrob24** [comment]
Ok I got the script added but it is not showing any output. I can't figure it out. It runs from the console with no issues.

![image](https://cloud.githubusercontent.com/assets/12749455/13508115/3a2ce5ea-e14b-11e5-904d-ccec29506de0.png)

![image](https://cloud.githubusercontent.com/assets/12749455/13508135/506872ac-e14b-11e5-9bda-73aff5f48096.png)

If I comment out lines 87-111 and run the script the message "Success - find execution history" will display, but will not with the lines not commented out. Additionally I noticed the value type of the return is a hashtable, not sure if that is causing a problem or not. 

![image](https://cloud.githubusercontent.com/assets/12749455/13508247/d2b16584-e14b-11e5-9d3e-766c1b9e3c4b.png)

Any ideas?

**Comment by 9whirls** [comment]
There were quite a few bugs regarding to command output. I even introduced more recently when I tried to solve the exsisting ones. I need to find a better way to re-write this part.

For now, please revert to commit b7b2dd1. The history function should work at that point.

**Comment by jrob24** [comment]
Thank you that resolved the issue.
