### ISSUE TITLE
permission issue

### ISSUE THREAD

**Issue by mikemast01** [vmware/webcommander#142]
I can run the script with my account that is admin on the server hosting webcommander and runs fine. When a user runs the script who is not an admin on the server I get 
![image](https://cloud.githubusercontent.com/assets/17012705/13508162/78ac09ea-e14b-11e5-8a57-70cbde2e2e36.png)

I set the webcommander folder to everyone has read\write access, same issue. Do the users have to be in a specific group on the server for the scripts to run properly?

**Comment by mikemast01** [comment]
I have added my user to the administrator of the webcommander server and still get same error.?

**Comment by mikemast01** [comment]
Never mind cancel this.  Issue was the user did not have permissions to that VM and that is what happens when the get-vm command cant find the VM.

Sorry about that.

**Comment by 9whirls** [comment]
No problem
