### ISSUE TITLE
SelectText (Walnut)

### ISSUE THREAD

**Issue by jrob24** [vmware/webcommander#144]
In older version of webCommander I would use the SelectText type to provide predefined options but it would still allow the end user to enter in their own value. Does this exist in Walnut and if so how does it work? Do I use ValidateSet for the predefined options? Do you have any pre-built scripts using this feature so I can take a look?

**Comment by jrob24** [comment]
Ok I found in the genDefJson.ps1 script it is looking for the name of the parameter to be datastore, portGroup, or vmName. I have set it to parameter name to datastore and the type is defined as selectText, but where can I how can I set the predefined options? I tried using ValidateSet but that locked in options and didn't allow to add anything custom.

![image](https://cloud.githubusercontent.com/assets/12749455/13583564/b1908cd4-e477-11e5-8daf-2229c03156cb.png)

**Comment by 9whirls** [comment]
ValidateSet in Powershell means the parameter value must be chosen from the set. No customized value is allowed.

**Comment by jrob24** [comment]
Yes I understand that. So how is the type SelectText used in Walnut? It does not appear to be any different than the type text. 

![image](https://cloud.githubusercontent.com/assets/12749455/13585162/cfeebd74-e47f-11e5-9627-19da9fa56c68.png)

Is it possible to do anything like this in Walnut? Predefined options with allowing custom input.

**Comment by 9whirls** [comment]
In master, there is no validateset defined in ps1 file. All options are defined directly in XML.
You could do the same thing in JSON for walnut.

**Comment by 9whirls** [comment]
Another option is to creat two parameters in ps1. One for the validateset and the other one for customized value.

**Comment by jrob24** [comment]
I am guessing if I did it in JSON it would require manually updating and maintaining the JSON files?

**Comment by 9whirls** [comment]
Yes, there isn't any automated way to do that. You need to manually add and maintain selectText info somewhere.

**Comment by jrob24** [comment]
Ok, where would I update the JSON files? I have the following but it isn't working as expected. 

    "name":"Datastore",
         "helpmessage":"Name of datastore to rename (Separate multiple datastores with comma)",
         "options":[
            "OLD_",
            "TR_"
         ],
		 "type":"selectText",
         "parametersets":[
            "RenameDatastore"
         ]
          },

**Comment by 9whirls** [comment]
Please get latest ui-min.js and try again.
![image](https://cloud.githubusercontent.com/assets/7997931/13616496/fe3a3f1e-e52e-11e5-94a3-8d4075fe9e61.png)

**Comment by jrob24** [comment]
Is that using type 'option' or type 'selectText' on storageFormat? I can get the option type to work using ValidateSet, but I am trying to get selectText to work with both predefined options and allow for user input.

**Comment by 9whirls** [comment]
Yes, if you change storageFormat into selectText, you could see the options and also all input.

**Comment by jrob24** [comment]
Ok I updated the ui-min.js and updated the _def.json and it does not allow input.

     {
            "name":"storageFormat",
            "helpmessage":"Storage format",
            "options":[
               "Thin",
               "Thick",
               "EagarZeroedThick"
            ],
            "type":"selectText"
         },

![image](https://cloud.githubusercontent.com/assets/12749455/13643364/040e97c0-e5e6-11e5-9634-083793a47934.png)

Am I missing something?

**Comment by 9whirls** [comment]
Nothing else. Is the change from option to selectText the only change you made to walnut code? If not, please try with the original code + this single change in _def.json.
