### ISSUE TITLE
gendefxml error

### ISSUE THREAD

**Issue by mikemast01** [vmware/webcommander#147]
the script was working fine a few hours ago, now i get errors and not sure why. 
objectps1 is still in the powershell folder same as Gendefxml script.
I even replaced the GenDefXML and the Objects.ps1 file with the originals and still get same error.

------------------------------------------------------------------------------------------------------------------
PS C:\Users\admmmasters.EMRSN> C:\WebCommander\powershell\genDefXml.ps1
. : The term '.\objects.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\WebCommander\powershell\genDefXml.ps1:37 char:3
+ . .\objects.ps1
+   ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\objects.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

writeCustomizedMsg : The term 'writeCustomizedMsg' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\WebCommander\powershell\genDefXml.ps1:193 char:1
+ writeCustomizedMsg "Info - copy current definition XML to _def-$timeSuffix.xml"
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (writeCustomizedMsg:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

writeCustomizedMsg : The term 'writeCustomizedMsg' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\WebCommander\powershell\genDefXml.ps1:208 char:1
+ writeCustomizedMsg "Success - generate command definition XML"
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (writeCustomizedMsg:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by 9whirls** [comment]
you need to run the script from c:\webcommander\powershell
cd c:\webcommander\powershell
.\gendefxml.ps1

**Comment by mikemast01** [comment]
duh, yeah I remember that.  It was giving me an error ealier when I right clicked and said run in powershell, but the screen disappeared.. so I was running it manually, and forgot to cd to directory.
It is fine now, I dont know why I was seeing "red" before when I right click on it, but its gone now.

Argh!  I had issues that disappear with no reason.  Thanks again.
