### ISSUE TITLE
Question: Browsing for a file

### ISSUE THREAD

**Issue by bvi1998** [vmware/webcommander#148]
Hi, 
I once figured out how you were allowing users to browse for files, but can no longer find that code... would you please tell me?
Thanks!

**Comment by 9whirls** [comment]
Do you mean the configuration of IIS that allows users view files in a folder on webcommander server?

**Comment by bvi1998** [comment]
no, sorry... when you let users browse out to grab a file they want to upload to a vm or so

**Comment by 9whirls** [comment]
Just add a parameter named "file" to your Powershell script.
https://github.com/vmware/webcommander/blob/master/powershell/VM/vmUploadFile.ps1#L83

**Comment by bvi1998** [comment]
Thanks!
