### ISSUE TITLE
Issue with running an exe

### ISSUE THREAD

**Issue by bvi1998** [vmware/webcommander#150]
Hi, 
I have a script where I am running an .exe which exists in c:\windows\system32 , but when I run the script from WebCommander it says it cannot be found:
C:\windows\system32\curltt.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
The script works outside of WebCommander just fine.

I set a variable with the entire command, then I run it with invoke-expression 
Any ideas? 
Thanks!

**Comment by 9whirls** [comment]
Please try "& c:\windows\system32\curltt.exe ..."

**Comment by bvi1998** [comment]
nope, does not work. Even if I just run curl.exe --help I still get curl.exe not found...

**Comment by 9whirls** [comment]
Does the user (as whom the powershell script runs) have right to access c:\windows\system32\curltt.exe?

**Comment by bvi1998** [comment]
I am not sure at this point who it is running as because I'm not sure if it has anything to do with the application pool identity. I am using my system account when I run it from WC. I did try notepad but it was hanging even though I used out-null.
Who might I be running as? The first part of the script runs other commands and psexec and they succeed. I have created a script now which does nothing but cd to Windows\system32 and runs the curl.exe with an XGET only. Super simple...
I really want to use WC it's a great interface for unknowledgeable people ;)
Thx!

**Comment by 9whirls** [comment]
writestdout $(whoami)
This command will display the user as whom the script is running.

Where is the psexec binary located on your server? Since psexec.exe could run, you could try moving curl.exe into the same folder. If it works, the user probably couldn't read c:\windows\system32\.

**Comment by bvi1998** [comment]
I could not seem to get around this. I ended up creating a script from the script I was running. For instance:

$checkentry =  @"

c:\scripts\auto\curltt.exe -XGET --negotiate -u : -blahblah

"@    

$checkentry | set-content c:\scripts\auto\checkhost.ps1 -Force

(get-content c:\scripts\auto\checkhost.ps1) | ? {$_.trim() -ne "" } | set-content c:\scripts\auto\checkhost.ps1 -Force

$result = & c:\scripts\auto\checkhost.ps1

Of course it's a long way around but works perfectly for curl. Invoke-WebRequest  or Invoke-RestMethod could have been a solution but it does not work in our environment. 

Thanks Jerry
