### ISSUE TITLE
Fail - add disk Cannot validate argument on parameter 'Datastore'

### ISSUE THREAD

**Issue by E-M** [vmware/webcommander#151]
This is not an issue with WebCommander but rather with my PowerCLI skills, but perhaps you can help me with this. I am trying to add disk to VM to other datastore then VM is located on. So I took vmAddDisk.ps1 script and modified it:

```
$vivmList = getVivmList $vmName $serverAddress $serverUser $serverPassword
$vivmList | % { 
	$vm = $_
    $cluster = Get-Cluster -VM $vm
    $datastore = Get-Datastore -Refresh -RelatedObject $cluster -Tag $diskType | sort FreeSpaceGB -Descending | Where-Object {$_.Name -like "r5-*"} | Select-Object -First 1
	(1..$diskNumber) | % {
		try {
			New-HardDisk -CapacityGB $capacityGb -StorageFormat $storageFormat -Confirm:$false -VM $vm -Persistence $persistence -Datastore $datastore -ea Stop
			writeCustomizedMsg "Success - add disk $_ to vm $vm"
		} catch {
			writeCustomizedMsg "Fail - add disk $_ to vm $vm"
			writeStderr
		}
	}
}
```

When I run this script directly on PowerCLI it works, but when I do it with WebCommander it fails with:

> Fail - add disk Cannot validate argument on parameter 'Datastore'. The argument is null. Provide a valid value for the argument, and then try running the command again.

So looks like $datastore variable does not have value. Any ideas?

**Comment by mikemast01** [comment]
do you run on powercli on the same server running web commander?  I use the writecustomizedmsg in my scripts when I troubleshoot to see if the variables are getting the correct info.
right before the try command could out put the variables tot he web commander screen using the writecustomizedmsg command to make sure they have the correct value and see if it is jus the $datastore or something else, say maybe the $cluster variable or another variable not getting populated corectly.

**Comment by 9whirls** [comment]
Please try running the script from powershell console. Your PowerCLI console may have extra settings not available to WebCommander.

I also have another concern about this. Please read on.

According to https://www.vmware.com/support/developer/PowerCLI/PowerCLI51/html/New-HardDisk.html, datastore parameter is of StorageResource type.

Get-Datastore returns Datastore which is not a StorageResource object.
https://www.vmware.com/support/developer/PowerCLI/PowerCLI50/html/Datastore.html

Not sure if this mismatch matters since you mentioned the script works in PowerCLI console

**Comment by E-M** [comment]
Hi, yes it works just fine when I do it from PowerCLI console which is on the same server as WebCommander:

```
PowerCLI C:\> $vm = "testvm01"
PowerCLI C:\> $storageFormat = "EagerZeroedThick"
PowerCLI C:\> $persistence = "Persistent"
PowerCLI C:\> $diskType = "backup"
PowerCLI C:\> $cluster = Get-Cluster -VM $vm
PowerCLI C:\> echo $cluster

Name                           HAEnabled  HAFailover DrsEnabled DrsAutomationLevel
                                          Level
----                           ---------  ---------- ---------- ------------------
Cluster_VC10                  True       1          True       FullyAutomated

PowerCLI C:\> $datastore = Get-Datastore -Refresh -RelatedObject $cluster -Tag $diskType | sort FreeSpaceGB -Descending | Where-Object {$_.Name -like "r5-*"} | Select-Object -First 1
PowerCLI C:\> echo $datastore

Name                               FreeSpaceGB      CapacityGB
----                               -----------      ----------
r5-datastore-1                   1 444,927      12 287,750


PowerCLI C:\> New-HardDisk -CapacityGB $capacityGb -StorageFormat $storageFormat -Confirm:$false -VM $vm -Persistence $persistence -Datastore $datastore -ea Stop

CapacityGB      Persistence                                                    Filename
----------      -----------                                                    --------
1,000           Persistent                [r5-datastore-1] testvm01/testvm01_1.vmdk
```

I also printed $cluster and $datastore variables in output and I see that $cluster variable is assigned correctly but $datastore variable is empty.

**Comment by mikemast01** [comment]
I ran you command thru mine but i had to take off the , -Tag and the where-Object , and it worked.

-------------------------------------------------------------------------------------
$vivmList = getVivmList $vmName $serverAddress $serverUser $serverPassword
$vivmList | % { 
	$vm = $_
	$cluster = Get-Cluster -VM $vm
    $datastore = Get-Datastore -Refresh -RelatedObject $cluster | sort FreeSpaceGB -Descending  | Select-Object -First 1
	writeCustomizedMsg "$cluster"
	writeCustomizedMsg "$datastore"
	(1..$diskNumber) | % {
		try {
			New-HardDisk -CapacityGB $capacityGb -StorageFormat $storageFormat -Confirm:$false `
				-VM $vm -Persistence $persistence -ea Stop
			writeCustomizedMsg "Success - add disk $_ to vm $vm.name"
-------------------------------------------------------------------------------------------------------
![image](https://cloud.githubusercontent.com/assets/17012705/13967918/a63fc04e-f047-11e5-9286-bb6a46c0d202.png)

**Comment by E-M** [comment]
Thanks. 
I just did some more tests and it did not even work with

`$datastore = Get-Datastore -Name r5-datastore-1`

May I ask what PowerCLI version do you have? I am using version 6.0.0-3205540. I suspect that this version is not really compatible with WebCommander.

**Comment by E-M** [comment]
Here is something weird from history file:

```
<result><customizedOutput>[2016-03-23 11:38:20] Success - connect to server vc-server</customizedOutput><customizedOutput>[2016-03-23 11:38:20] Info - server is of product line: VPX</customizedOutput>
Get-Datastore : 23.03.2016 11:38:20    Get-Datastore        You are not currently connected to any servers. Please connect firs
t using a Connect cmdlet.
At C:\WebCommander\powershell\VM\MyvmAddDisk.ps1:74 char:18
+     $datastore = Get-Datastore -Name r5-datastore-1
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Get-Datastore], ViServerConnectionException
    + FullyQualifiedErrorId : Core_BaseCmdlet_NotConnectedError,VMware.VimAutomation.ViCore.Cmdlets.Commands.GetDatastore

<customizedOutput>[2016-03-23 11:38:21] Fail - add disk Cannot validate argument on parameter 'Datastore'. The argument is null. Provide a valid value for the argument, and then try running the command again. to vm testvm01, cluster Cluster_VC10, datastore </customizedOutput>
<stderr><exceptionType>System.Management.Automation.ParameterBindingValidationException, System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35</exceptionType><fullyQualifiedErrorId>ParameterArgumentValidationError,VMware.VimAutomation.ViCore.Cmdlets.Commands.VirtualDevice.NewHardDisk</fullyQualifiedErrorId><errMessage><![CDATA[Cannot validate argument on parameter 'Datastore'. The argument is null. Provide a valid value for the argument, and then try running the command again.]]></errMessage><scriptName>C:\WebCommander\powershell\VM\MyvmAddDisk.ps1</scriptName><scriptLineNumber>77</scriptLineNumber><offsetInLine>132</offsetInLine></stderr>
</result>
  <returnCode>4444</returnCode>
```

Any idea why:

> You are not currently connected to any servers.

**Comment by 9whirls** [comment]
Add -server parameter to the command.

**Comment by E-M** [comment]
Thanks! That did the trick and it works now!
