### ISSUE TITLE
Upload file error

### ISSUE THREAD

**Issue by bvi1998** [vmware/webcommander#154]
When I run the upload file script using a csv file it gives me the following message:

C:\WebCommander\powershell\VM\vmUploadFile.ps1 : Cannot bind argument to
parameter 'file' because it is an empty string.At line:1 char:182
+ ... mm11done -file '' -destination c%3A%5Ctemp%5C

If I run the same script with a .log file it gets past the above message (but does fail with missing parameters, which I am less concerned about for now) ... 

Do you have an idea about this? 
Thanks!

**Comment by 9whirls** [comment]
If you pass the path of a file to the file parameter, it won't work. You need to pass a real file object.

**Comment by bvi1998** [comment]
Sorry, I don't understand what you mean. 
I have $file as a parameter and browse for the file. 
Then I want to import the file contents, so I do this: $objects = Import-CSV $file
Is that incorrect?
Thanks!

**Comment by 9whirls** [comment]
Could you upload CSV file to a VM with the built-in vmUploadFile command?
https://github.com/vmware/webcommander/blob/master/powershell/VM/vmUploadFile.ps1

**Comment by bvi1998** [comment]
I just tried uploading a text file and received this message:
result>
    <stdOutput><![CDATA[C:\WebCommander\powershell\VM\vmUploadFile.ps1 : Cannot bind argument to
parameter 'file' because it is an empty string.At line:1 char:193
+ ... mm11done -file '' -destination c%3A%5Ctemp%5C
+                    ~~
    + CategoryInfo          : InvalidData: (:) [vmUploadFile.ps1], ParameterBi
   ndingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAl
   lowed,vmUploadFile.ps1

]]></stdOutput>

I browsed out to a text file, same as my other attempts. 
Thanks for your help!

**Comment by 9whirls** [comment]
Please check if the file has been uploaded to www\upload\<client_ip>\ folder.

**Comment by bvi1998** [comment]
ok that was it, the upload folder did not exist. 
Thanks!
