### ISSUE TITLE
Question : Remove the hyperlink to see the code

### ISSUE THREAD

**Issue by bvi1998** [vmware/webcommander#155]
Hi, 
Can you tell me how to remove the hyperlink to the script at the top of WebCommander? I like to see the script name and directory, but do not want to allow anyone to open it. 
Thanks!

**Comment by 9whirls** [comment]
Remove line 84 - 86
https://github.com/vmware/webcommander/blob/master/www/webCmd.xsl#L84

**Comment by bvi1998** [comment]
this did not work... it's 84-86?

**Comment by 9whirls** [comment]
Yes, it is. The link should not work anymore. We basically removed the href parameter from it.
