### ISSUE TITLE
Question: Would it be possible to add a script description area? 

### ISSUE THREAD

**Issue by bvi1998** [vmware/webcommander#156]
Hi,
Would it be possible to add a frame(?) above the parameter/value/help message where I can comment on the script with special notes, etc? 
Sorry, I don't know html at all, so cannot modify even if I wanted to ;) 
Thanks!

**Comment by 9whirls** [comment]
Click the question icon. It shows the script/command description. You could add description in ps1 file as illustrated in wiki and run genDefXml to re-generate webcmd.xml. You could also update <description> section for the command in webcmd.xml directly.
