### ISSUE TITLE
Bit.ly scripts?

### ISSUE THREAD

**Issue by seiniku** [vmware/webcommander#157]
[Why use bit.ly?](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fvmware%2Fwebcommander%2Fcommit%2F1e56423719678ef5ef557adf012b6d4ff1ee06dd&sa=D&sntz=1&usg=AFQjCNHF48EgOQTBZ-e8vCC0aDimA0v7LQ)

This looks very sketchy. Why isn't this ui-min.js file just in a www/scripts folder within this git repo? A bit.ly link to a file on dropbox? Meant to be used for a ui that deals with usernames and passwords (in plain text!) for central infrastructure? Not ok in my book.
I'd prefer to see a non-minimized, local file managed by git

**Comment by Mads** [comment]
I share this observation, makes it even more sketchy that there is not even a comment...

**Comment by seiniku** [comment]
No kidding. #wontfix
At least the dropbox file is obfuscated. Nothing to see there, certainly.

**Comment by 9whirls** [comment]
Walnut is designed to support running Powershell scripts from internet. Those scripts on dropbox could be considered as examples, but not a required part of this project. You could simply remove them from sources.json.

**Comment by seiniku** [comment]
-<link href="//dl.dropbox.com/s/zcbtbm6mzuz5vtk/ui-min.css" rel="stylesheet" />
 -<script src="//dl.dropbox.com/s/rz4h4cdjmtxmhkd/ui-min.js"></script>
 +<link href="//bit.ly/21D9Urd" rel="stylesheet" />
 +<script src="//bit.ly/1LTCYPC"></script>

This is in reference to the ui-min.js file, which does appear to be required for the ui
