### ISSUE TITLE
Question: Open html page after execution

### ISSUE THREAD

**Issue by bvi1998** [vmware/webcommander#160]
Hi, 
One of my scripts goes and gets information from a Linux box and displays the output in an html file. 
Is there a way to launch this file from WebCommander when the script has completed? Or, just embed the html into the results? 
Thanks!

**Comment by 9whirls** [comment]
First of all, you must output the URL to the html in your PS1 script. So the user could open the page with it.

If you want the redirect to happen automatically, you need to add codes as below in webcmd.php
header("Location: url_to_the_html");
die();
