### ISSUE TITLE
use WebCommander with internet access limited (no bit.ly url)

### ISSUE THREAD

**Issue by Tonic8** [vmware/webcommander#162]
Hello

the internal policy prohibit us to use bit.ly url.

<link href="//bit.ly/21D9Urd" rel="stylesheet" />

<script src="//bit.ly/1LTCYPC"></script>

is there a way for the data to be available on the github and dowloadable with the full archive.

At least the bit.ly short url.

Regards.
Tonic

**Comment by 9whirls** [comment]
Please use code from master branch.

**Comment by Tonic8** [comment]
just downloaded it. Sorry newby on github and default branch was set on "Walnut".

**Comment by 9whirls** [comment]
Master branch meets your requirements better since it's fully self contained.
