### ISSUE TITLE
Browser Plugin not installing.

### ISSUE THREAD

**Issue by mikemast01** [vmware/webcommander#173]
Jerry,
have you had/heard of any issues with the VMRC browser plugin for Firefox not installing on windows 10 machines?  I have a colleagues that are having issues getting the plugin installed.  
From vcenter webclient all the consoles work, web console, remote console... but when they try to launch from wecommander page it says no valid plugin.  Seems people with windows 7 install the VMRC and it installs the plugin fine.
I worked on this for a few hours yesterday and could not get it to work thru webcommander. and wanted to see if you have seen this.

Mike

**Comment by 9whirls** [comment]
Hi Mike,
In PowerCLI 6.5, VMRC is no longer a browser plugin but a program installed at c:\program files (x86)\VMware\Infrastructure\PowerCLI\Modules\VMware.VimAutomation.Core\VMware Remote Console\vmrc.exe.

http://webcommander.eng.vmware.com/webcmd.php?command=vmRemoteConsole could generate vmrc URL for VM as below:
vmrc://clone:cst-VCT-52861707-6ac1-d9bf-ce5e-6ffa02887e40--tp-59-1A-58-19-CE-CA-96-AA-72-68-D5-04-D1-57-1D-12-D1-BD-32-29@a.b.c.d:443/?moid=vm-441

You could feed that URL to vmrc.exe to open VM console.

**Comment by mikemast01** [comment]
We are still on 6.0… not sure about powerCLI.. haven’t updated it in a while.
Anyone with the browser plugin already webcommander still works. Anyone new cant get the browser plugin installed even with a VMRC 8.1 install.

Is there going to be an update to that script for console in webcommaned to address this in the future you know?  OR something we are going to have to work thru ourselves.
☺

Thanks

Mike Masters | VMware  | Converged Infrastructure
Emerson | 8000 W. Florissant Ave. | St. Louis | MO | 63136 | USA
T +1 314.553.2542 | F + 1 314.553.1491 | M +1 314.502.8914
CompTIA | A+ , Net + , Sec. +
VMWare | VCP 3,4,5   VCAP5-DCA
MCITP | 2008 SA/VA
-----------------------------------------------------------------------------------------------
For non-urgent concerns, contact Emerson’s IT Service Desk.
Employee Self Service:
http://itservicedesk.emrsn.org/webtier-9.30/ess.do

For urgent concerns:
Service Desk Phone Numbers:
+1 866 457 4877 (US) | +63 2 982 2300 (Manila, Philippines) | +40 364 731010 (Cluj, Romania)

**Comment by 9whirls** [comment]
I'm afraid that this issue of VMRC browser plugin could not be addressed from webcommander perspective. Webcommander simply generates URL for triggering VMRC but has nothing to do with installation or configuration of VMRC.

**Comment by mikemast01** [comment]
I was thinking that…

Thanks will have to look into creating a link with instructions on how to use that with the VMRC.

Mike Masters | VMware  | Converged Infrastructure
Emerson | 8000 W. Florissant Ave. | St. Louis | MO | 63136 | USA
T +1 314.553.2542 | F + 1 314.553.1491 | M +1 314.502.8914
CompTIA | A+ , Net + , Sec. +
VMWare | VCP 3,4,5   VCAP5-DCA
MCITP | 2008 SA/VA
-----------------------------------------------------------------------------------------------
For non-urgent concerns, contact Emerson’s IT Service Desk.
Employee Self Service:
http://itservicedesk.emrsn.org/webtier-9.30/ess.do

For urgent concerns:
Service Desk Phone Numbers:
+1 866 457 4877 (US) | +63 2 982 2300 (Manila, Philippines) | +40 364 731010 (Cluj, Romania)
