### ISSUE TITLE
Powercli script addition

### ISSUE THREAD

**Issue by tharunkumarholiga** [vmware/webcommander#175]
Hi,

I am not so good in scripting/Programming. I am leaning Powecli. I want use webcommander for few of my executions.

1. How to remove the scripts and Icons from the Webcommander page. (which are not required)
2. Can we restrict access to only few users.  so that only few can execute the scripts.
3. I have a powercli script for execution of few queries on vROPS. So how to incoporate the script in the page.

**Jerry, I contacted you 1:1 emails twice earlier.

Please suggest me if you have docs/sites which can help me in learning apart from the git hub links.

Thanks,
Tharun Kumar
tharunkumar.holiga@gmail.com

**Comment by 9whirls** [comment]
Please read https://github.com/vmware/webcommander/wiki/Installation-and-configuration-guide for authentication and add / remove scripts.

**Comment by tharunkumarholiga** [comment]
Hi Jerry,

I don't see this file in webcommander folder "powershell_def.xml"

Thanks,
Tharun Kumar

**Comment by 9whirls** [comment]
There is no such a file, but _def.xml under www/.

**Comment by tharunkumarholiga** [comment]
Hi Jerry,

I searched www/ and see only 3 XML files. May be the one I downloaded is
having issues.

I need to go with New installation.

**Comment by tharunkumarholiga** [comment]
Please ignore my email I got it " c:\webcommander\www\webcmd.xml"

On Wed, Mar 15, 2017 at 12:11 AM, Tharun Kumar <tharunkumar.holiga@gmail.com
