### ISSUE TITLE
The term 'connect-VIServer' is not recognized as the name of a cmdlet,

### ISSUE THREAD

**Issue by vmpowercli** [vmware/webcommander#181]
Could not able to connect any vCetner from Webcommander portal, I get this error every time when I try to connect 

"The term 'connect-VIServer' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

C:\WebCommander\powershell\objects.ps1
--
scriptLineNumber | 190
-- | --
offsetInLine | 15

I did added the "Import-Module VMware.VimAutomation.Core" at the beggning of the script but no luck :( 

Any help is appreciated  !!

Thank You

**Comment by 9whirls** [comment]
What's the version of powercli installed on webcommander server?

**Comment by vmpowercli** [comment]
VMware PowerCLI 6.5 Release 1 build 4624819

**Comment by vmpowercli** [comment]
Okay, I removed Powercli 6.0 and installed 5.5.. Its working now.

Any plans for releasing future versions which are compatible with 6.0 or above ? 

Thank You for your help

**Comment by 9whirls** [comment]
It sounds weird. My understanding is powercli 6+ uses module and 5.5 uses snapin. What you observed is just opposite.
