### ISSUE TITLE
Scripts not showing

### ISSUE THREAD

**Issue by potatoucsd** [vmware/webcommander#184]
Thanks for this wonderful tool; I hope to use it soon!  I ran the installer and after completion I noticed a couple of things:

1. I can't see any of the powershell scripts in the browser.  I only see Perl, Python, Ruby as the filter commands and the respective examples.  Client is Chrome 63.0.3239.108
2. When trying to secure the site with https the formatting gets messed up (left Filter Commands navigation menu doesn't work).

Server is Windows Server 2012 R2 with latest security updates.

**Comment by 9whirls** [comment]
1. click on the builtin command "generate command definition" and then go back to the home page.
When you add new powershell scripts into webcommander, use this method to make it show up on the home page. For details, refer to https://github.com/vmware/webcommander/wiki/Generate-_def.xml-directly-from-Powershell-scripts

2. use developer console of chrome and firefox to debug this issue. See if any javascript could not be loaded when you use https. This article may also help. https://ssbkang.com/2014/02/11/webcommander-ssl-certificate-installation/

**Comment by potatoucsd** [comment]
Great, I should have seen #1 in the wiki.  Thanks.

Now when I am looking at the html and style sheets it is interesting because it looks like it is reaching out to external sites for the javascript.  I guess I will tweak it for my needs.
