### ISSUE TITLE
Question on new fields?

### ISSUE THREAD

**Issue by vmikemast** [vmware/webcommander#186]
I am setting up webCommander at a new company, and download the latest code.. I see 2 new parameters on every command page.. "InformationAction"  and "InformationVariable"...  can you explain what these are for?   maybe I need to refresh myself on updated documents?   LOL

Thanks for any info...
Mike Masters

**Comment by 9whirls** [comment]
Add those two parameter names here
https://github.com/vmware/webcommander/blob/master/powershell/genDefXml.ps1#L122

$commonParam = @("InformationAction","InformationVariable", ... )

And then re-run genDefXml. Simply click the link of "generate command definition" on the home page.

**Comment by 9whirls** [comment]
Since I already left vmw, I'm not able to update this project on github any more. 
Congrats on your new job!

**Comment by vmikemast** [comment]
AH, did not know you left.  Thanks for the info

**Comment by vmikemast** [comment]
Jerry, how do I go about geting rid of these 2 on each page? It is not something I will use any time soon and would like for the fields to not show up..

Thanks

**Comment by 9whirls** [comment]
Open your _def.xml file, remove those from parameters section.
Or make the change in gendefxml.ps1 as showed in comment 2, and re-run it to generate the xml file again.

**Comment by vmikemast** [comment]
If I remove from _def.xml, and then run gendefxml.ps1 it puts those parameters back into _def.xml.
Ok sorry I did not realize the change from comment 2 would remove those 2 fields.

It is now done.. Thanks Again for all the assistance on this project.
Mike Masters
