### ISSUE TITLE
time out waiting for return

### ISSUE THREAD

**Issue by vmikemast** [vmware/webcommander#187]
I know I have asked this before and I cant find the answer in the previous issues...   where was it again to up the time out value?  I believe the default is 300 seconds

Thanks
Mike Masters

**Comment by 9whirls** [comment]
php.ini

**Comment by vmikemast** [comment]
Thank you sir.   Glad to talk to you again.. been a little while.

**Comment by 9whirls** [comment]
Yep, quite a while. It's good to know that long time users still use this tool. Thanks a lot!

**Comment by vmikemast** [comment]
Yes sir.. bringing it into a new company and they like it also.  Thanks for being there to answer questions when needed.
Mike Masters
