### ISSUE TITLE
Poker for stop-vmguest

### ISSUE THREAD

**Issue by TKOED** [vmware/webcommander#188]
Hi, I am new to webcommander,  I can see under the "VM" section a click option for "Shutdown VM".
When testing this seems to do a stop-vm.  Is there a way to add a Poker for a graceful shutdown using
stop-vmguest ?

**Comment by 9whirls** [comment]
You could either replace stop-vm with shutdown-vmguest or call vm.stop() function.

Here are some examples https://github.com/9whirls/webcommander_walnut/blob/master/powershell/vSphere/VM/object.ps1#L55
https://github.com/vmware/webcommander/blob/master/powershell/objects.ps1#L422

**Comment by TKOED** [comment]
Thanks for your response, looks very straight forward and appreciate your time
