### ISSUE TITLE
Installing on Windows Server 2012

### ISSUE THREAD

**Issue by bvi1998** [vmware/webcommander#189]
Hi, has anyone had any luck using the setup.ps1 to install WC on Windows 2012? I have had many problems, starting with IIS not installing properly. 
I installed in manually according the manual directions but Web Platform installer has failed many times, I guess due to some issues at SourceForge.
One problem in trying to access the website is the error:
PHP Notice: Undefined index: command in C:\Webcommander\www\webCmd.php on line 159
Thanks for any help!

**Comment by 9whirls** [comment]
There is a detailed guide for manual installation https://github.com/vmware/webcommander/wiki/Installation-and-configuration-guide
Please try to follow the instructions and see if you could get it installed successfully.

As for the PHP error, what's the version of PHP you installed? Please try PHP 5.3 if you installed another version.

**Comment by bvi1998** [comment]
Thanks. I have done the exact instructions and parts have failed. The install feature with sub features fails to install everything due to a windows error which requires me to try the dism command to specify the source of the software, the web platform installer won’t install php and especially php manager. So as I work through all of this I guess I need to know where I might find the php iis manager, and how to manually install php for use with WC, and what settings I might need in IIS for php to work. I did use a php version 5.3.x..
Thanks!

**Comment by bvi1998** [comment]
Closed by accident ;)

**Comment by 9whirls** [comment]
https://docs.microsoft.com/en-us/iis/configuration/system.webServer/fastCgi/

**Comment by 9whirls** [comment]
That web page describes How to create a global FastCGI handler mapping for PHP

**Comment by bvi1998** [comment]
Thanks. I am almost there. The website comes up. I want to run the gendefxml but receive this error:
. : AuthorizationManager check failed.
At line:1 char:3
+ . 'C:\Windows\SysWOW64\WindowsPowerShell\v1.0\profile.ps1'**

I am not using the administrator ID for security, I am using a different id with admin privileges. I'm not sure where this is going wrong. Just a little more help please ;) 
Thanks!

**Comment by 9whirls** [comment]
http://tgnp.me/2011/09/powershell-authorizationmanager-check-failed-resolution/
It could be an execution policy issue. Login as the user and set-executionpolicy to unrestricted.

**Comment by bvi1998** [comment]
ok now I have moved on to execute the gendefxml script and am getting this error:

Get-Help could not find C:\Webcommander\powershell\Windows\changeName.ps1 in a help file in this session. To download updated help topics type: "Update-Help". To get help online, search for the help topic in the TechNet library at http://go.microsoft.com/fwlink/?LinkID=107116.

 I have removed most of the scripts so it is actually only looking at the Windows folder and scripts. 

Thanks!

**Comment by 9whirls** [comment]
cd c:\webcommander\powershell
$cmd = get-command .\Windows\changeName.ps1
$help = get-help $cmd.definition

Please run the commands above in powershell console. If you encounter the same problem, try upgrade powershell and also run update-help.

**Comment by bvi1998** [comment]
your three lines of code worked perfectly. I did not need to update help. 

I'm running: 
Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1

**Comment by 9whirls** [comment]
Did you run the commands as the same user?
If so, I don’t understand why you saw the error previously.

**Comment by bvi1998** [comment]
I am logged on locally to the server as the administrative user. I was able to perform the first that you asked. Then I upgraded Powershell, then updated help. Now I am failing on enablerdp.ps1. If I run:
cd c:\webcommander\powershell
$cmd = get-command .\Windows\enablerdp.ps1
$help = get-help $cmd.definition

I received the message Get-Help could not find c:\webcommander\powershell\Windows\enablerdp.ps1 in a help file in this session.

Thanks for your help!

**Comment by 9whirls** [comment]
It’s a credential issue I believe because you could run as administrator but not the other user.

**Comment by bvi1998** [comment]
Now I am at the point that I try to run the genDefXML and get:

Result

[2018-03-12 11:06:44] Fail - run command


I do ctrl-u and don't get anything interesting.... thoughts? 

Actually it's still related to the help file.

C:\WebCommander\powershell\Windows\changeName.ps1 in a help file in this session. To download updated help topics type:

This occurs if I run it as myself (I'm in the local admin group) and also as the administrator equivalent user id I am using.

Thanks!

**Comment by bvi1998** [comment]
Ok I figured out the help problem. I had to unblock all of the files in the webcommander\powershell folder:

Get-ChildItem -Recurse | Unblock-File
