### ISSUE TITLE
\WindowsPowerShell\v1.0\profile.ps1

### ISSUE THREAD

**Issue by bvi1998** [vmware/webcommander#192]
Hi, 
I do not want to use default passwords, I would like the user to enter it each time. 
In the case of the Powershell Profile, where is this used, and how to I get around having to use a default password? Is this for authenticating to vmware? Again, I do not want to have a default pwd.
[Reflection.Assembly]::LoadWithPartialName('system.web') | out-null
add-pssnapin vmware* -ea SilentlyContinue
$env:defaultPassword = ''
Thanks for any help!

**Comment by 9whirls** [comment]
Simply make it a mandatory parameter

**Comment by bvi1998** [comment]
Yes, that's the first thing I did but am getting a message about power
shell  x86 profile insecure auth.

**Comment by bvi1998** [comment]
Thanks, I missed one where I should have written mandatory
