### ISSUE TITLE
External Link HelpMessage

### ISSUE THREAD

**Issue by jrob24** [vmware/webcommander#198]
Is it possible to embed an external link in the helpmessage attribute on the parameter tag? For example I would like to link to a sample file used by the script. If not in the helpmessage is there another spot where this could be linked on a per script basis?

**Comment by 9whirls** [comment]
You could update webcmd.xsl for this. Please refer to https://github.com/vmware/webcommander/blob/master/www/webCmd.xsl#L75 through line 89. You need to do similar transformation for helpmessage.
