### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by bvi1998** [vmware/webcommander#202]
Hi, 
As my script is going through the process of building a vm, eventually I get this. Is there any logging I can use to debug this? 
500 - Internal server error.
There is a problem with the resource you are looking for, and it cannot be displayed. Also I  don't get the output xml file in history.

Thanks!

**Comment by 9whirls** [comment]
How long does your script need to run?
And what's the value of max_execution_time in your php.ini?

**Comment by bvi1998** [comment]
Here is the setting in the PHP.INI under [WebPIChanges]

max_execution_time=300

The customization process does take a very long time....

**Comment by 9whirls** [comment]
The max_execution_time should be longer than what's required to run the customization process.

**Comment by 9whirls** [comment]
![image](https://user-images.githubusercontent.com/7997931/45577098-32cbf080-b82f-11e8-941a-09d8aec13ce7.png)
Please also make sure the fastcgi timeout setting is configured accordingly.

**Comment by bvi1998** [comment]
Thx I’ll try that!

**Comment by bvi1998** [comment]
I made these changes and the issue remained. I did have a lot of write-host messages which I had used for testing the script in PS while waiting for customization, plus a transcript was running which was stopped at the end. After I removed the chatter and stopped the transcript things seemed to work. Thanks for your help.
