### ISSUE TITLE
WorkFlow - Import JSON

### ISSUE THREAD

**Issue by bvi1998** [vmware/webcommander#204]
Hi, 
Every time I import a json file to create a workflow, it imports it twice into 1 workflow. Have you seen this? 
Thanks!

**Comment by 9whirls** [comment]
Is this about walnut? This version only supports xml but not json.

**Comment by bvi1998** [comment]
no, it's not about Walnut. It is json...
Thanks

**Comment by 9whirls** [comment]
JSON is not supported
