### ISSUE TITLE
External Web Dependencies

### ISSUE THREAD

**Issue by JimmyAstle** [vmware/webcommander#24]
I would like to use this software on my internal ESX environment which doesnt have internet access. In inspecting the page source there are references to fonts.googleapis.com, jquery themes, and twitter api widgets that never load causing very bad lag when loading webcommander.

Was webcommander ever intended to work in a non-internet connected environment? If not then this issue can be closed.

**Comment by 9whirls** [comment]
You could download those external files and reference to them locally.

**Comment by JimmyAstle** [comment]
I will take care of that on Monday and get back to you.

**Comment by JimmyAstle** [comment]
Went ahead and downloaded the multiple versions of jquery and there dependencies. I commented out the links to the google fonts as well. UI worked as advertised.
