### ISSUE TITLE
Dynamic list of VM's in parameter section

### ISSUE THREAD

**Issue by Nordal** [vmware/webcommander#52]
Hi all.

I'm not sure if this should be in the issue section, but i dont see any other place to put it.
My thought is that it would be nice to be able to populate the vm list from a vcenter when filling out the parameters e.g. when doing a snapshot.
I was thinking about some onclick JavaScript thing that would get the list from the vcenter stated in the serverAddress field, and populate it as a list in the vmName field.

I'm not that familier with powershell, but i have been working with PHP where i did this alle the time, just fetching data from a database.I have been looking at the dymanic parameters here: http://stackoverflow.com/questions/22993799/ but im not sure how to integrate it in webcommander. Maybe someone in here could help me out?

Best Regards - and thanks for the great work so far.
Kasper Lund
KMD - Denmark

**Comment by 9whirls** [comment]
Hi Kasper,

Have a look at the command deployOvaToVc. There are two buttons "list datastore" and "list port group". The do very similar to what you suggest here.

Since we already have the listVmAndSnapshot command, to populate all VMs on a VC should be easy to implement. I believe you just need to add a function in webcmd.js and add a button in webcmd.xsl

**Comment by Nordal** [comment]
Hi 9whirls, 

Thank you for your reply, unfortunately i am not even able to figure out where the actual buttons are implemented in the deployOvaToVc.ps1 file :(
Could you please give me some more hints?

Thanks, Kasper

**Comment by jrob24** [comment]
Following this topic as I am having the same issue. I have updated the webcmd.xsl for the new button, but having issue trying to create the button for webcmd.js. I am new to jscript so trying to figure out the right syntax to get it to display and work properly.

**Comment by jrob24** [comment]
Doing some testing with the 'List Portgroup' button with the deployOvaToVc.ps1 I cannot get anything to load. The button changes to Loading....but never brings back any results. I never see the session log into vCenter with the specified user creds either.

**Comment by 9whirls** [comment]
Hi Kasper,
The buttons are not implemented in powershell script. webcmd.xsl defines the buttons themselves and webcmd.js defines the button actions.

**Comment by 9whirls** [comment]
jrob24, you are Jason from wells fargo, right?
Please open developer console in your browser and then click the button again.
It will trigger an AJAX call. If anything goes wrong, you should see error messages there.

**Comment by 9whirls** [comment]
Guys, please check out the latest code that including fix or datastore and portgroup buttons and also the new button to list VM

**Comment by jrob24** [comment]
I just applied your updates and still cannot get a list from the datastore or portgroup buttons. You mentioned a developers console to see if I am getting an errors. How can I access that?

**Comment by 9whirls** [comment]
Have you re-run genXmlDef command?
You should be able to get a list of datastores as showed below

![listdatastore](https://cloud.githubusercontent.com/assets/7997931/8095006/9f68e4b6-0f7f-11e5-9748-1cb3439af494.png)

You could open the web console from developer menu on Firefox.

![webconsole](https://cloud.githubusercontent.com/assets/7997931/8095027/cf661328-0f7f-11e5-95e8-8b961ec8fa7c.png)

**Comment by jrob24** [comment]
Yes I reran genXmlDef. It looks like it tries to run listdatastore, but never actually does and just times out.

![listds](https://cloud.githubusercontent.com/assets/12749455/8095350/09361b94-0f93-11e5-9ac4-ede1aae83565.png)

**Comment by 9whirls** [comment]
Weird, is the listDatastore command available on your server and working well?

**Comment by jrob24** [comment]
Yea that is definitely the problem. I am unable to execute listDatastore (and other WC scripts) from WC but I can run it from a PS console with no problems. I am able to execute several scripts that I wrote and added to WC with no issues. It is very strange that I am able to execute my scripts but not WC scripts. It just spins and never outputs any error messages.

**Comment by 9whirls** [comment]
It sounds we have a different problem now.

If you need me to help on it, please open another issue and provide me more details there.
For instance, could you run built-in webcommander scripts from powershell console?

**Comment by jrob24** [comment]
Yes I can run built in WC scripts from a PS console and I can run my scripts from WC and PS Console.

**Comment by 9whirls** [comment]
That doesn't make sense to me. We have to have look on your server to understand what's going on.

**Comment by Nordal** [comment]
Hi.
I have tried the code, and it seems to be working for me. But it is extremely slow. I have around 1400 VM's, and it will be in the "loading" process for several minutes (and ends up with an undefined error) get-vm directly in PC will run around 30 sek. (get-vm).Count returns 1416.

**Comment by 9whirls** [comment]
It's slow because the listVmAndSnapshot command also looks for VM IP address and snapshots.
You could comment out line 81 to 92 in listVmAndSnapshot.ps1 and try again.

**Comment by Nordal** [comment]
I tried commenting out the suggested lines, but it seems to have no effect on the behavior?

**Comment by 9whirls** [comment]
Please run the script in powershell console as below:
Cd C:\webcommander\powersshell
.\vsphere\listvmandsnapshot.ps1

Let me know how long it takes to run.

**Comment by Nordal** [comment]
When i try to run the script it exits the PowerCLI/PowerGUI Script Editor and i am not able to see the error text. By the way, my listvmandsnapshot.ps1 is location in the VM folder and not the vsphere - dont know if that changes anything.

Do you have any overall documentation regarding how the different files interact with one another, it woul be a great help in doing new enhancements like this one.

**Comment by 9whirls** [comment]
My fault. VM folder is correct. I was asking how much time it takes to run the script.
If it takes much time, you need to edit php.ini to enlarge the timeout setting.
Have a look at this https://github.com/vmware/webcommander/issues/62

**Comment by Nordal** [comment]
The script exists with an error within 1 second, and i am not able to see the error message.

**Comment by jrob24** [comment]
Are you running the script with all of the required parameters? 

\vm\listvmandsnapshot.ps1 -serverAddress vCenter -serverUser User1 -serverPassword Pass -vmName VM

**Comment by 9whirls** [comment]
Just a small tip. If you launch powershell from CMD and run script there, poweshell will still exit but you could view the output in CMD.

**Comment by Nordal** [comment]
As the runtime for getting the VM list is so slow, i thought about creating the list by a scheduled task twice a day or so with this: get-vm | Select-Object name > c:\%vcname%_vmlist.csv.

Then i need to populate the correct list from what i choose in the serverAddress field. So if i choose VC1 in the serverAddress field, the vmName should be populated with the content from VC1_vmlist.csv

Would this be possible?

**Comment by 9whirls** [comment]
All command results are saved on the server as XML under www/history folder.
You could just show others the latest result.

**Comment by Nordal** [comment]
Hi again. After some debugging I found that the "select -uniq" function was the sinner. When having more than 1400 VM's it's a very slow process. Commenting the line out reduced runtime from 3+ min to 25 sec. :)
Depending on our time we will try to implement a select box, that will pop up thje list of VM's in a windows and enabling the operator to pick out the targets, and move them to a selected list. This will come in very handy when running scipts on multiple machines in multiple clusters.

**Comment by 9whirls** [comment]
Glad to know you have found the root cause.
Please also notice that vmName field supports multiple values and wildcards, such as "win2008*, server*".
