### ISSUE TITLE
Unable to get installed...

### ISSUE THREAD

**Issue by barnette08** [vmware/webcommander#53]
So I have installed IIS and attempted to install PHP but web installer fails with a "Unable to download the product list from ." error.

After that I went ahead and looked at the web commander script that looks like it attempts to do the same for you but it seems to fail too.  I have already installed the latest PowerCLI build and the below is the output of the webcommander setup script.

Downloading PowerCLI, WPI and Advanced Logging...
         PowerCLI, WPI and Advanced Logging downloaded successfully.
Downloading WebCommander package...
         WebCommander package downloaded successfully
IIS is already installed.
Web Platform Installer is already installed.
WARNING: PowerCLI installer is not available.
WARNING: Please download and install PowerCLI manually.
Installing PHP...
WARNING:   Failed to install PHP.
WARNING:   Please install it manually, and run this script again.

**Comment by 9whirls** [comment]
If setup.ps1 doesn't work well on your server, please follow the instructions below to deploy webcommander manually.
https://github.com/vmware/webcommander/wiki/Installation-and-configuration-guide
