### ISSUE TITLE
PowerShell script parameters 

### ISSUE THREAD

**Issue by jrob24** [vmware/webcommander#54]
I am attempting to use the file type to upload a file to www/upload for searching. I noticed that when I name my script parameter was named $File, WC never created the folder in www/upload, however when I named it $file it worked as expected and created the directory and uploaded the file. Are the script parameter names case sensitive?

**Comment by 9whirls** [comment]
Yes, because both PHP and XML are case sensitive.
The parameter case doesn't matter in Powershell, but it matters in the _def.xml.

**Comment by jrob24** [comment]
Ok should I only use lower case for parameter names in the _defs.xml?

**Comment by 9whirls** [comment]
Sure, it makes things easier.
