### ISSUE TITLE
DOCTYPE declarations

### ISSUE THREAD

**Issue by jrob24** [vmware/webcommander#55]
If I wanted to use DOCTYPE declarations do they need to be added to _def.xml? If so I am guessing they would need to be added to genDefXml.ps1 to be generated?

**Comment by jrob24** [comment]
I believe I figured this out, however I am sure there is a more elegant way to accomplish this.

**Comment by 9whirls** [comment]
I'm not quite sure about what you want to accomplish.
If you still need my assistance, please provide more details.

**Comment by jrob24** [comment]
In previous versions you used DOCTYPE declarations for commonly used parameters in webCmd.xml. Here is an example:

<!DOCTYPE webcommander [
  <!ENTITY commonViServerParam '
		<parameter optional="0" name="serverAddress" description="IP or FQDN of the ESX or VC server where the target VM is located" />
		<parameter optional="1" name="serverUser" description="User name to connect to the server (default is root)" type="selectText">
			<options>
				<option value="root">root</option>
				<option value="administrator">administrator</option>
			</options>
		</parameter>
		<parameter optional="1" name="serverPassword" description="Password of the user (default is VMware standard)" type="password" />
  '>

I have several entities that I used in the older version and wanted to migrate over to the latest version. It does not appear like you are using entities anymore and have rolled everything into PS script parameters. I still have a use for them and wanted to make sure I added them back successfully. Since _def.xml is overwritten I needed to find a way to add it to genDefXml.ps1. I use something that will work for me, but maybe an additional for anyone that wants to use going forward might be helpful.

**Comment by 9whirls** [comment]
I see. You should be able to add that in webcmd.xml which will not be modified by genDefXml.ps1.

**Comment by 9whirls** [comment]
Hi Jason,
I got your email. I will answer your question here because other users may see it.
I feel the easiest way to address your requirement is to keep using your original webcmd.xml.
You could use genXmlDef to generate definitions for newly added powershell scripts by adding the entry below in your webcmd.xml

<xi:include href="../powershell/_def.xml" xpointer="xpointer(//command)" parse="xml" />

Then you will have both legacy compatibility and automatic _def.xml generation.
