### ISSUE TITLE
Missing an argument for parameter file

### ISSUE THREAD

**Issue by bvi1998** [vmware/webcommander#60]
I want to get a csv file name from the user, then use that file as input to a powershell script. I can do this on my desktop by calling the script with the expected file parameter. How do I perform this in WebCommander? I am using the $file variable which allows me to browse for the file. But the script cannot see this file (Missing an argument for
 parameter ‘file’. Specify a parameter of type ‘System.String’ and try again).
 Hope this makes sense.
 Thanks,
Jen

**Comment by jrob24** [comment]
Hey Jen,

Can you share how you are calling the $file in your script?

**Comment by bvi1998** [comment]
sure :)

Param (
    [parameter(
        Mandatory=$true,
        HelpMessage="File to input"
    )]
    [string]$file
)

foreach ($paramKey in $psboundparameters.keys) {
	$oldValue = $psboundparameters.item($paramKey)
	$newValue = [system.web.httputility]::urldecode("$oldValue")
	set-variable -name $paramKey -value $newValue
}

. .\objects.ps1

$filename = import-csv $file
Foreach ($f in $filename)
{ do something }

**Comment by jrob24** [comment]
Ok that looks good, webCommander should be creating a directory under /www/upload with the ip address of the source uploading the file. The file will be uploaded to that directory. My suspicion is those directories are not being created, if so then it might be a permission issue depending on how you have WC configured to run.

**Comment by bvi1998** [comment]
ok thanks. The directory is not being created. I will check the permissions.

**Comment by 9whirls** [comment]
Jen, please create the upload folder in www and try again.

**Comment by 9whirls** [comment]
Jason, thanks a lot for helping other users. Please keep doing that. :)

**Comment by bvi1998** [comment]
That worked, creating the folder. 
Thanks!
Jen
