### ISSUE TITLE
xlink help

### ISSUE THREAD

**Issue by jrob24** [vmware/webcommander#64]
I am trying to create a hyperlink using xlink in the helpmessage of the paramater tag in the webcmd.xml. 

I have added the namespace here:

`<webcommander `
			`xmlns:xi="http://www.w3.org/2003/XInclude"`
			`xmlns:xlink="http://www.w3.org/1999/xlink">`

However I am unsure how to link to the helpmessage. Here is an example:

`<parameter name="file" helpmessage="File must be .txt and contain single column of server names" mandatory="1" type="option" />`

I would like to link the word .txt to a sample file. I have tried several things based off of research but I am not having any success. Do you have any experience using xlink and can it be used in this situation?

**Comment by 9whirls** [comment]
As far as I know, no browser supports xlink in xml file.
You should add the link in webcmd.xsl but not webcmd.xml.
Please refer to line 77 - 82 about how to add a link.

**Comment by jrob24** [comment]
Ok I will play around and see what I can figure out.
