### ISSUE TITLE
File name with spaces

### ISSUE THREAD

**Issue by jrob24** [vmware/webcommander#65]
Any file name with spaces always errors out. My guess is because the parameter value needs quotes " " around it for powershell to interpret it as one string. I was looking to see if the webcmd.php could be updated to always place quotes " " around the file name regardless of spaces or not as I think that would resolve the issue. 

I am not that good with php, so any insight would be greatly appreciated.

**Comment by 9whirls** [comment]
You are right. Do you want to contribute the fix? If so, just change line 231 as below
$cmd .= " -" . $name . " '" . realpath($fileName) . "'";

**Comment by jrob24** [comment]
Absolutely, just need to figure out how to do that...

**Comment by 9whirls** [comment]
Great. I will leave the fix to you. Enjoy your self git training journey.
