### ISSUE TITLE
[enhancement] Datetime type option

### ISSUE THREAD

**Issue by jrob24** [vmware/webcommander#68]
Would it be possible to add date\time parameter option that provided a calendar to select a date and time to schedule a job? I have a script we use to create vCenter scheduled tasks and using a calendar to select the date\time would be extremely beneficial and keep the format consistent.

**Comment by 9whirls** [comment]
The easiest way is to use HTML5 input types for this
http://www.w3schools.com/html/html_form_input_types.asp.

We need to make two updates 
1. define a paramter type as datetime in _def.xml
2. transform it as &lt;input type="datetime-local" /&gt; in webcmd.xsl

**Comment by jrob24** [comment]
That was easy, unfortunately it is only supported by Chrome and not FF or IE. I need a solution that works for all 3. I am thinking I need to use JQuery in order to accomplish this.

**Comment by 9whirls** [comment]
I will address this requirement in the new UI design I'm currently working on.

**Comment by jrob24** [comment]
Ok thank you! I was able to add a datepicker using the following:
https://jqueryui.com/datepicker/

However I have not had any luck with a timepicker or datetimepicker. Looking forward to the update.

**Comment by 9whirls** [comment]
The new UI will be a complete change.
If you already add the datepicker based on current UI, you could merge in the code immeditely. There is no need to wait for my update.

**Comment by jrob24** [comment]
So I may have spoke too soon. While I have the datetpicker working it doesnt appear to be passing any data back to the script parameter. 

Here is what I have in the following files:
_def.xml
`<parameter name="date" helpmessage="Select date and time to schedule" mandatory="0" type="date" />`

webcmd.xsl
`<xsl:when test="@type = 'date'">
						<input type="datetime-local" />`

I am running a basic script to just write the $date parameter back to the host and out-file. It never generates any results and when I view the source nothing is there either.

**Comment by 9whirls** [comment]
Post your code to your own repository and send me the link.

**Comment by 9whirls** [comment]
I have integrated datetimepicker into walnut.
![image](https://cloud.githubusercontent.com/assets/7997931/12902894/ba5853e8-ce78-11e5-8175-6329d5c9069a.png)
