### ISSUE TITLE
Blank Page  in webcommander

### ISSUE THREAD

**Issue by JessicaSarah** [vmware/webcommander#69]
![error](https://cloud.githubusercontent.com/assets/13317044/8655484/fe65b4b4-29ae-11e5-82b4-ccdbbb6c3654.png)
Source Code of the page:

<?xml version="1.0"?>

<?xml-stylesheet type="text/xsl" href="index.xsl" ?>
<webcommander xmlns:xi="http://www.w3.org/2003/XInclude">
  <command name="genDefXml" synopsis="Generate command definition" developer="liuj@vmware.com" xml:base="../powershell/_def.xml">
    <description>This command generates _def.xml.
It parses all powershell scripts to get information from comment
based help and parameter attributes.</description>
    <script>genDefXml</script>
  </command>
</webcommander>

screenshot attached. The entire installation was done using  install.ps1 at 
https://github.com/vmware/webcommander/blob/master/powershell/Install/setup.ps1

The usual site shows all those scripts .I have tried this on 2008,2012 and win7 everywhere same problem .

**Comment by 9whirls** [comment]
I don't see any screenshot. 
Please run the following commands in powershell console. 
CD c:\webcommander\powershell
.\genXmlDef. Ps1

Then refresh the webpage.

**Comment by JessicaSarah** [comment]
Screenshot attached.This is what i get on powershell 


PS C:\webcommander\powershell> .\genDefXml.ps1
You must provide a value expression on the right-hand side of the '-' operator.
At C:\webcommander\powershell\genDefXml.ps1:128 char:15
+             if ($name - <<<< in $commonParam){continue}
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : ExpectedValueExpression

**Comment by 9whirls** [comment]
First of all, the "blank" page showed in the screenshot is expected. Once you click on "Generate command definition", the command will parse all powershell scripts under webcommander\powershell to re-create _def.xml. Then you will get the full command list. Once you add new scripts in, just click the command to make them visible.

The '-' operator issue is owing to low powershell version on your server, please upgrade to Powershell 4.0.

**Comment by JessicaSarah** [comment]
Thankx will check and let u know

**Comment by JessicaSarah** [comment]
Thankx for the help  its working fine .Appreciate it
