### ISSUE TITLE
Forcing 64bit powershell ?

### ISSUE THREAD

**Issue by steveyeomans** [vmware/webcommander#74]
Hi.

Having a issue trying to import and run a module that required 64bit powershell.

Error is: import-module : The current processor architecture is: X86.  The module requires the following architecture: Amd64.

Any ideas how to force webcommander to use the 64bit powershell.exe 

Cheers

Steve

**Comment by 9whirls** [comment]
Hi Steve,
Currently, PHP for IIS is only available in 32 bit. 
Although there is an x64 PHP on http://windows.php.net/, it also says "The x64 builds of PHP for Windows should be considered experimental, and do not yet provide 64-bit integer or large file support". 
Without x64 PHP, we couldn't launch x64 Powershell from webcommander.

If you don't use Windows authentication integrated in IIS, you could try to replace IIS with Apache so that you could use x64 PHP to launch x64 Powershell.

**Comment by steveyeomans** [comment]
Thanks Jerry,

Will give apache a go but I did manage a workaround – using webcommander 32 bit to call the 64 bit powershell script:

c:\windows\Sysnative\windowsPowershell\V1.0\PowerShell.exe "C:\WebCommander\powershell\vSphere\64bitpowershell.ps1"

**Comment by 9whirls** [comment]
I tried the same trick before. It didn't work for me. 
If I run the the following command from x86 powershell console
c:\windows\system32\windowspowershell\v1.0\powershell.exe -command "ls env:"
The output still shows "PROCESSOR_ARCHITECTURE x86", which means the x64 powershell is not launched at all.

**Comment by steveyeomans** [comment]
Try using sysnative from the x86 console as below (note sysnative not system32) ☺

c:\windows\sysnative\windowspowershell\v1.0\powershell.exe -command "ls env:"

PROCESSOR_ARCHITECTURE         AMD64

**Comment by 9whirls** [comment]
You are right. "Sysnative" is the correct path to use. And it does launch the x64 powershell.

I also notice that this change could make the command performance worse. For instance, the showHistory command took about 9 seconds before the change, but now it takes 13 seconds. 
If you have a clue about this, please let me know.

**Comment by steveyeomans** [comment]
Hi Jerry

The extra time will probably be because of the extra time to open a new powershell thread.

I only use the change for scripts that use 64 bit modules and keep everything else at 32 bit

So for example I have one script that needs 64 bit and call it as such – tintrirepl.ps1 calls the below tintrirepl1.ps1:

## Author: Jerry Liu, liuj@vmware.com

foreach ($paramKey in $psboundparameters.keys) {
                $oldValue = $psboundparameters.item($paramKey)
                $newValue = [system.web.httputility]::urldecode("$oldValue")
                set-variable -name $paramKey -value $newValue
}

. .\objects.ps1

$results = & c:\windows\sysnative\windowsPowershell\V1.0\PowerShell.exe "C:\WebCommander\powershell\vSphere\tintrirepl1.ps1"

[array]$replicationVMs=@()
foreach ($result in $results) {
                $replicationVMs += $result
}

writeStdout $replicationVMs

**Comment by 9whirls** [comment]
What I did is changing line 210 of webcmd.php to below
$cmd = "set runFromWeb=true & c:\\windows\\sysnative\\windowspowershell\\v1.0\\powershell .\\" . $scriptName . ".ps1";
So there is no new thread opened.

**Comment by vLifeOfBrian** [comment]
Is x64 support going to be added to webCommander? I don't see this line added to webcmd.php in the repo? Or will it be added to the new version of webCommander?

**Comment by 9whirls** [comment]
Considering it's Steve who found the solution, I wish he would update the code and send me a pull request.
If this won't happen when I release the new version, I will add it in.

In case you need the x64 support immediately, please just modify the code as I mentioned in my previous comment.

**Comment by vLifeOfBrian** [comment]
Thanks Jerry!

**Comment by 9whirls** [comment]
My pleasure :)

**Comment by steveyeomans** [comment]
Hi All,

To run 64 bit shell as is without changing any of the default files:

Script 1 is the 32 bit script that is called via webcomander:
Script 2 is the 64 bit script called by script one and its results are stored in the $results variable
Script 1 reads results, formats them if required and outputs to web

Sample script 1
$results = & c:\windows\sysnative\windowsPowershell\V1.0\PowerShell.exe "C:\WebCommander\powershell\vSphere\script2.ps1"
foreach ($result in $results) {
                $output += $result
}
writeStdout $output

Sample script 2
# do the 64 bit stuff (module below is 64 bit only)
import-module "C:\Program Files\TintriPSToolkit\TintriPSToolkit.psd1"
get-tintrivm


hope that helps !

**Comment by 9whirls** [comment]
It's helpful for sure. The sysnative way is easier. 
If you don't want to update webcommander code, I'll add it in anyway.

**Comment by steveyeomans** [comment]
I should add that Jerrys edit is of course cleaner but as Jerry highlighted changing everything to 64bit shell increases the runtime.

Hence I left the defaults as is so the runtime only increases on the specific scripts that need 64 bit shell.

Jerry – if you need me to do a pull request please advise how as I have no idea ☺

Cheers

Steve

From: Yeomans, Steve
Sent: 02 November 2015 19:17
To: 'vmware/webcommander'; vmware/webcommander
Subject: RE: [webcommander] Forcing 64bit powershell ? (#74)

Hi All,

To run 64 bit shell as is without changing any of the default files:

Script 1 is the 32 bit script that is called via webcomander:
Script 2 is the 64 bit script called by script one and its results are stored in the $results variable
Script 1 reads results, formats them if required and outputs to web

Sample script 1
$results = & c:\windows\sysnative\windowsPowershell\V1.0\PowerShell.exe "C:\WebCommander\powershell\vSphere\script2.ps1"
foreach ($result in $results) {
                $output += $result
}
writeStdout $output

Sample script 2
# do the 64 bit stuff (module below is 64 bit only)
import-module "C:\Program Files\TintriPSToolkit\TintriPSToolkit.psd1"
get-tintrivm


hope that helps !

**Comment by 9whirls** [comment]
Hi Steve,
Please refer to github help about creating a pull request
https://help.github.com/articles/using-pull-requests/

Looking forward to seeing you in the contributor list!
