### ISSUE TITLE
Execute workflow as a web service

### ISSUE THREAD

**Issue by HonkIfULuvBrian** [vmware/webcommander#77]
Is it possible to execute a workflow command as a webservice? I have attempted to call a command from vCO in a RESTful way using https:/hostname.com/webCmd.php?command=runWorkflow as an endpoint. 

The command completes, but returns the _def.xml files as the output. When you look at the command history the Result Code is the xml file(output-1438952925.xml) and nothing is in the file column. 

I would like to be able to execute a command as a webservice externally and pass JSON variables to it and retrieve the results back into vCO. 

URL:
https://hostname.com/webcmd.php?command=runWorkflow&name=listDatastoreWorkflow&type=serial&actionOnError=stop&workflow=%5B%7B%0D%0A%09%22command%22%3A+%22listDatastore%22%2C%0D%0A%09%22serverAddress%22%3A+%22%22%2C%0D%0A%09%22serverUser%22%3A+%22%22%2C%0D%0A%09%22serverPassword%22%3A+%22%22%2C%0D%0A%09%22variableList%22%3A+%22%22%2C%0D%0A%09%22wf_des%22%3A+%22%22%0D%0A%7D%5D&workflowUrl=

**Comment by 9whirls** [comment]
Here is an example in powershell

$workflowJson = '
[{
	"command": "listDatastore",
	"serverAddress": "a.b.c.d",
	"serverUser": "root",
	"serverPassword": "password"
}]
'
$body = @{command="runWorkflow";name="workflow-name";workflow=$workflowJson}
$r = invoke-webrequest -uri "https://hostname.com/webcmd.php" -body $body -method post
$r.content
