### ISSUE TITLE
Other Powershell Modules for utilization of webcommander

### ISSUE THREAD

**Issue by jmannor** [vmware/webcommander#80]
i have been messing with Webcommander for a while now getting used to it and how it functions. This tool is going to be great i can see it. 

I am having an issue trying to use other Powershell Modules for lets say Netapp Filers or the Active Directory Module. and still running everything in 32 bit mode still functions the way i need it to but when trying to run the same scripts from webcommander it Runs a success but doesn't seem to run the script at all. 

Keep in mind i am trying to run different modules in powershell an example of what i go it below.

Param (
    [parameter(
        Mandatory=$true,
        HelpMessage="Which OU to change the accopunts passwords?"
    )]
    [string]
        $OU, 

```
[parameter(
    Mandatory=$true,
    HelpMessage="Set the password you want the accounts to be changed to"
)]
 [string]
     $Password
```

)

foreach ($paramKey in $psboundparameters.keys) {
    $oldValue = $psboundparameters.item($paramKey)
    $newValue = [system.web.httputility]::urldecode("$oldValue")
    set-variable -name $paramKey -value $newValue
}

. .\objects.ps1

Import-Module ActiveDirectory
# 

start-sleep -s 5
# 

Get-ADUser -filter "enabled -eq 'true'" -SearchBase "OU=XXXXX,OU=XXXX,DC=XXXX,DC=XXXX,DC=XXXX,DC=com"

any assistance and or help with this is appreciated

**Comment by 9whirls** [comment]
After runing the command, right click on the page and select "view source".
Let me know if you see any error message there.

BTW, I tested running the following command on my server
get-aduser -filter 'samAccountName -like "*"'
It worked well. 
So I believe what you met is a configuration issue.

**Comment by jmannor** [comment]
<result>WARNING: Error initializing default drive: 'Unable to contact the server. This may be because this server does not exist, it is
 currently down, or it does not have the Active Directory Web Services running.'.
Get-ADOrganizationalUnit : Unable to contact the server. This may be because this server does not exist, it is currently down,
or it does not have the Active Directory Web Services running.


I do see this as an error but i have checked the Domain serves themselves making sure ADWS is there and running. not too sure now

but thank you for the help

**Comment by 9whirls** [comment]
That sounds an authentication issue. What authentication method you configure on IIS?
If anonymous authentication is used, set it run as administrator.

**Comment by jmannor** [comment]
It was set for windows Authentication. but enabling anonymous Authentication and the specifying a user it worked just fine.

thank you for the simple solution

thanks again

Jordan Mannor
Netapp system administrator

**Comment by 9whirls** [comment]
My pleasure.
