### ISSUE TITLE
Clear text password in www/history folder

### ISSUE THREAD

**Issue by Nordal** [vmware/webcommander#86]
I really hate to see my own password in clear text, especialy when it's not me typing in into the wrong field, as username or whatever.
I am very amazed to see my password in the history folder, why is it there?

I thought the time where security was not highly prioritized was over - do you have any plans to fix this?
BTW, why is passwords handled in cleartext at all?

I hope this is fixed very soon.

BR, Kasper

**Comment by 9whirls** [comment]
You could change line 235 in webcmd.php as below:

if ($param["type"] != "password") {
  $param->addAttribute("value", $req[$name]);
}

**Comment by Nordal** [comment]
Great, but why is this not the default setting?

**Comment by Nordal** [comment]
This is my line 235 now:
			if ($req[$name] != "") {
				$cmd .= " -" . $name . " " . urlencode($req[$name]); 
				$url .= "&" . $name . "=" . urlencode($req[$name]);
Should i replace all of it?

**Comment by 9whirls** [comment]
https://github.com/vmware/webcommander/blob/master/www/webCmd.php#L235
