### ISSUE TITLE
Newbie... 

### ISSUE THREAD

**Issue by TrotmanRalph** [vmware/webcommander#89]
Ran the scripted and manual install but neither show me any powershell.  I see filters for Perl,Python and Rugby.  I can add commands using Perl,Python or Ruby but no powershell.

  My system has powershell 4 and powercli 5.8 but its like something is missing.   I'm using win2012 r2

Thanks.

**Comment by TrotmanRalph** [comment]
After it failed adding an command.. I was able to see all other types...


Thanks.

**Comment by 9whirls** [comment]
Maybe you would provide me an opportunity to help next time :)
