### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by Nordal** [vmware/webcommander#94]
Hi again.

we have been working with Webcommander for some months now, and have implemented several functions for our support to use - thats great. But we do have one really big issue, performance.
Logging in to vcenter and pulling a list of VM's from a powercli shell takes around 4 seconds.
Doing the same thing through webcommander takes around 20 seconds. We have created a function to extend disks where we populate all vm's from  vcenter in a select list, and pull out the disk info from the VM selected in the list. Populating the list is around 20 seconds and getting disk info is another 20 seconds of waiting, resulting that no one wants to use our webcommander :(

How can we debug where the issues are? Do you have any suggestions in how to speed things up?

Best regards, Kasper

**Comment by 9whirls** [comment]
https://github.com/vmware/webcommander/issues/62
please have a look at the above issus report. It mentions a few common ways to debug performance.

if your script runs ok in console but slow in webcommander, it is likely to have some time consuming commands in your powershell profile.

**Comment by Nordal** [comment]
I actually saw the other issue just after i posted my message. Thanks for answering, I will look at it next week.

**Comment by Nordal** [comment]
HI again. I tried to find the holy grail in #62 but there are actually a lot of different solutions, and my results are not identical. I have two users in my domain, a std. user and a domain admin user, normally i use the domain admin user for running scripts and managing vsphere. Therefore i also ran webcommander with my admin user, this is slow. I tried adjusting the global profile, adjusting IE settings etc. but i did not get any improvements.
Then i tried to add my std. user to the administrators group (which my domain admin account also is a member of but through an AD group) and logging in, without adjusting profile, IE or anything else i suddenly saw great performance improvement? I tried to reproduce the setup with a colleage, but had no success.

All in all i can verify that there are some kind of user/rights issues, but i am not able to fix it. 

Do you have any good suggestions?

My webcommander server is running Server 2012R2

**Comment by 9whirls** [comment]
Would you please test if the steps below?

Open IIS
Find the application pool
Right click and choose advance
Set  "Load user profile" to "false"

**Comment by Nordal** [comment]
Load user profile on the "DefaultAppPool" was already set to false.
But as at least one user in #62 experienced, the changes suddenly "kicked in". I have now cut 2/3 of my execution time, which is not awesome, but acceptable.

**Comment by 9whirls** [comment]
It seems we still haven't found the root cause. It's hard to do performance tuning without access to the server. If you want to further invesigate this, please setup a webex session so that we would able to debug on the server together.
